### ISSUE TITLE
constraints and objective functions in a matrix form for MOO? can we use for loops to iterate over Decision variables and create constraints

### ISSUE THREAD

**Issue by sqiprasanna** [anyoptimization/pymoo#154]
Hi, @julesy89 , Thank you for creating this wonderful library.
I have few questions I mentioned below. Please help me out :
Let me know If I'm doing this the correct way or not
Ex:- I have 10 Decision variables and I've divided the first 6 D.V. to Obj Fn 1 (created using:- lambda x:x[:6]) and the rest 4 to Obj Fn 2(lambda x:x[6:])). 

I have another array that needs to be multiplied with Obj Fn1 & 2  i.e., 
Ex:- Y=[np.arange(10)] (**CONSTANT ARRAY NOT DECISION VARIABLE**)
My Obj Fn1 :- np.sum(x[:6]*Y[:6])
My Obj Fn2 :- np.sum(x[6:]*Y[6:])

I have used for loop to overcome this.
```
objs = [
lambda x: np.sum(x[:6]*Y[:6])
lambda x: np.sum(x[6:]*Y[6:])
]
n1,n2=6,4
i=0
constraint_ieq=[]
while i<10:
     if i<6:
           n=6
     else:
           n=4
           constraint_ieq.append(lamda x: np.sum(x[i:i+n]*y[i:i+n]) -2           #Is this right?? x[0]*y[0]+x[1]*y[1]+x[2]*y[2]+x[3]*y[3]
     i+=n
```
2. Is there a way to write the above method into a functional problem or a Class problem?
3. In functional Problem, Is there a way to pickle lambda functions we define for constraints and objectives as I'm getting the below error while checkpointing the algorithm? I defined the constraints in functional problem format.

Update:-
I have changed the Functional problem to Class problem. lambda error got fixed but I cannot save checkpoint 2nd time after loading and running the minimize function. np.save --> np.load --> run minimize from checkpoint--> np.save  (Not working, No error too but file size is ~6KB where initially it's ~415MB)

**Comment by sqiprasanna** [comment]
And If possible please let me know If I'm writing the constraint correctly or not?
My Decision variables are binary and I converted X into 2 D array for 
Ex:- [True,False,True,False,True,False,True,False,False] to [[True,False,True],[True,False,True],[True,False,False]] I need to write a constraint such that each row should have only 1 True or all False.
xi+x[i+1]+x[i+2] >=0
xi+x[i+1]+x[i+2] <=1
code:-
`
for i in range(0,len(x),3):
    constraint_ieq.append(-np.sum(x[i:i+3]))
    constraint_ieq.append(np.sum(x[i:i+3])-1)
`

**Comment by julesy89** [comment]
What is your concrete question? 

Reshaping and looping over constraints as you are doing it is possible.

**Comment by sqiprasanna** [comment]
let's say my Decision variables will be x1 to x9.(3*3)
For shop1 ,
    x1+x2+x3 >=0
    x1+x2+x3 <=1 ... so on
How do I write the above constraint in code? 
```
for i in range(0,9,3): # 3 shops, 3 choc, 9 D.V. 
    const.append(-np.sum[i:i+3])
    const.append(-1+ np.sum[i:i+3])

```
I wrote as below but still, this constraint is not validated while running the code. (Am I doing the correct way or not?)
I got output violating the above constraint something like [True,False,True,False,True,False,True,False,False] (where first 3 DV's has 2 Trues) 

and initial population generated for NSGA-II . Is it random initialization or Is there a way that it generates population based on constraints?

**Comment by julesy89** [comment]
Yes, I have written a tutorial for biased initialization here: https://pymoo.org/customization/initialization.html

For you problem I recommend to custimize a GA. For instance as shown here: https://pymoo.org/customization/subset_selection.html

You can check `res.CV` of the output and get the constraint violation or `res.G` for the exact `G` values. 



Your constraints correctly implemented look as follows:

```

import numpy as np
from pymoo.algorithms.so_genetic_algorithm import GA
from pymoo.factory import get_problem, get_sampling, get_crossover, get_mutation
from pymoo.model.problem import Problem
from pymoo.optimize import minimize

N = 3
n_var = N ** 2


class MyProblem(Problem):

    def __init__(self):
        super().__init__(n_var=n_var,
                         n_obj=1,
                         n_constr=N,
                         xl=np.zeros(n_var),
                         xu=np.ones(n_var),
                         elementwise_evaluation=True)

    def _evaluate(self, x, out, *args, **kwargs):
        f1 = float(- x.sum())
        out["F"] = f1

        n_ones = x.reshape((N, N)).sum(axis=1)

        out["G"] = (1 - n_ones) ** 2


problem = MyProblem()

algorithm = GA(
    pop_size=100,
    sampling=get_sampling("bin_random"),
    crossover=get_crossover("bin_hux"),
    mutation=get_mutation("bin_bitflip"),
    eliminate_duplicates=True)


res = minimize(problem,
               algorithm,
               seed=1,
               verbose=True)

print("Best solution found: \nX = %s\nF = %s" % (res.X, res.F))

print(res.X.reshape(N ,N))

```

**Comment by sqiprasanna** [comment]
Thanks, @julesy89 this worked. But how did out["G"] = (1-n_ones)**2 worked ? it gives me an array 
Ex:- [ True  True False False  True False False False  True] --> [2 1 1]**2 --> [1 0 0]. How is this same as   0<= x1+x2+x3 <=1 ?
I just wanted to know because I have few other constraints to write in this way. 

_Make sure whatever you store in `out["F"]` has the size as `len(X)`.

Otherwise, I would need a source code snippet to reproduce your error.

_Originally posted by @julesy89 in https://github.com/msu-coinlab/pymoo/issues/26#issuecomment-587109458__

In the above issue, you mentioned out["F"] should have len(X). 
but can I divide X=10 into two  different sets (x1=6,x2=4) and create an objective function 
I have the below use case. I need to maximize f1, f2. Let me know if I wrote it correctly or not
f1 = x1*const1[0]+x2*const1[1] .... + x6*const1[5]
f2 = x7*const2[0]+x8*const2[1] .... + x10*const2[3]
```
x1 = x[:6].reshape(2,3)
x2 = x[6:].reshape(2,2)
const_1 = np.random.rand(2,3)
const_2 = np.random.rand(2,2)
f1 = - np.sum(np.multiply(x1,const_1)).sum()
f2= - np.sum(np.multiply(x2,const_12)).sum() 
out["F"] = [f1,f2]

#constraint 1
# 0<=x1+x2+x3 <=1 , ... so on as explained above
constr1 = (1 - x1.sum(axis=1)) ** 2
constr2 = (1 - x2.sum(axis=1)) ** 2

# constraint 2
a1 = [0,1,2]
a2 = [0,1,2]
# 0<= x1*a[0] <=4 , 0<= x1*a[0] +x2*a[1] <=4 ,0 <=x1*a[0]+x2*a[1]+x3*a[2]<=4
for i in range(len(a)):
     constr3.append(x1[i]*a[i])

out["F"] = np.column_stack([f1,f2])    # throwing me an error population size 

```
I'm confused in some cases you have summed up along the axis and in some cases summed up all values for constraints and Obj fns.
Can you help me understand when to use axis-wise sum and other ways as well?

**Comment by julesy89** [comment]
I think the code above does not exaclty what you want.
Look at the code below:

```
def _evaluate(self, x, out, *args, **kwargs):
    f1 = float(- x.sum())
    out["F"] = f1
    n_ones = x.reshape((N, N)).sum(axis=1)
    out["G"] = (n_ones - 1)
```

1. Calculate the row sum by `x.reshape((N, N)).sum(axis=1)`.
2. We allow them to be feasible of 0 or 1, but consider them as infeasible or bigger `(n_ones - 1)`

The >= 0 is irrelevant, because the sum of zeros can not be less than zero.

**Comment by sqiprasanna** [comment]
Thanks for the reply @julesy89, (1-n_ones)**2 also worked for me. but anyway I'll check out that again it's a small issue. However, what I'm concerned about is that as decision variables increase NSGA takes a lot of time to get a feasible set of solutions. The convergence rate is also very slow. and also GA gives us a set of feasible solutions. but I got only a 2-5 set or even only 1 solution. which is definitely not the best solution(maybe sub-optimal). I tried fine-tuning n_gen and pop_size but I result is the same. What do you suggest in this case? Is pymoo scalable for huge set of Decision variables? If so what is the work around?   customizing GA or any other methods that I can try?
