### ISSUE TITLE
possibility of Pymoo to work within a candidate search space 

### ISSUE THREAD

**Issue by MohamedRagabAnas** [anyoptimization/pymoo#171]
Hello, 
I have a problem of two objective functions, three variables, and zero constraints.
I have also a search space for these variables read from CSV. 
Is it possible to use pymoo to use that search space of variables (instead of xl, and xu) to get the best combination of them that maximize the two functions.
```python
class MyProblem (Problem):
  def __init__(self):
    super().__init__(n_var=3,
                     n_obj=2,
                     n_constr=0,
                     #I want to use the search space of the three variables (I already have)
                     xl=np.array([0.0,0.0,0.0]),
                     xu=np.array([1.0,1.0,1.0])
                     )
  def _evaluate(self,X,out,*args,**kwargs):
    #Maximizing the triangle area of the three variables
    f1=-1*(0.5*math.sin(120)*(X[:,0]*X[:,1] +X[:,2]*X[:,1]+X[:,0]*X[:,2]))

    #maximizing the sum of the variables
    f2 = -1*(X[:,0]+X[:,1]+X[:,2])

    out["F"] = np.column_stack([f1, f2])
    
problem = MyProblem()
```

When I use the xl and xu, it always gets the combination of ones [1.0,1.0,1.0], but I want to get the best combination out of my numpy multi-dimension array.
```python

import csv
with open("sample_data/dimensions.csv", 'r') as f:
    dimensions = list(csv.reader(f, delimiter=","))

import numpy as np
dimensions = np.array(dimensions[1:])
dimensions=np.array(dimensions[:,1:], dtype=np.float)

dimensions
```
that looks like the following:
```
array([[0.27      , 0.45      , 0.23      ],
       [0.        , 0.23      , 0.09      ],
       [0.82      , 0.32      , 0.27      ],
       [0.64      , 0.55      , 0.32      ],
       [0.77      , 0.55      , 0.36      ],
       [0.25      , 0.86      , 0.18      ],
       [0.        , 0.68      , 0.09      ],...])
```

Thanks for your help!

**Comment by julesy89** [comment]
Your result is that what you can expect. Analyze your objectives, and you will see each objective function has its optimum at (1,1,1). Thus, your objectives are not conflicting, and there exists an optimal solution dominating all others.

I recommend thinking one more time about the optimization problem to identify the trade-off in your problem.

**Comment by MohamedRagabAnas** [comment]
@julesy89  Thanks for your reply, yes I agree, but what I need is is there a way not to provide the upper bounds and lower bounds using ```xl``` and ```xu```, so that the algorithm is able to use the search space of the three variables read from the CSV (as shown above).

**Comment by julesy89** [comment]
You can pass `xl` and `xu` in the constructor of your problem. Both vectors can be loaded from a csv without any problem.

**Comment by MohamedRagabAnas** [comment]
Excuse me, How will it look like should I pass them the same values from CSV? I'm a little bit confused.

**Comment by julesy89** [comment]
I hope you have resolved your problem. If you only want a linear combination of the rows in the csv file you will have to redefine your problem to use them. Use the instructor of the problem to load files.

Julian
