### ISSUE TITLE
Problem.type_var not set

### ISSUE THREAD

**Issue by altaris** [anyoptimization/pymoo#185]
Hello,

In [`Problem.__init__`](https://github.com/anyoptimization/pymoo/blob/8430f219f3e8bbb2c9beba82b3cb49fa1000ec2d/pymoo/core/problem.py#L15), the kwarg argument `type_var` is unused. It is specified by certain descendent of `Problem`, e.g. [`CTP`](https://github.com/anyoptimization/pymoo/blob/8430f219f3e8bbb2c9beba82b3cb49fa1000ec2d/pymoo/problems/multi/ctp.py#L19) and [`ZDT`](https://github.com/anyoptimization/pymoo/blob/8430f219f3e8bbb2c9beba82b3cb49fa1000ec2d/pymoo/problems/multi/zdt.py#L10).

Is this attribute useful? If so, I think that
1. it deserve to by explicitly specified in [`Problem.__init__`](https://github.com/anyoptimization/pymoo/blob/8430f219f3e8bbb2c9beba82b3cb49fa1000ec2d/pymoo/core/problem.py#L15) rather than hidden in `**kwargs`;
2. documented.

If it is not useful, would it deserve to be removed altogether?

Best,

C

**Comment by julesy89** [comment]
Good point. So far, it is only used as a type "hint" when a problem is defined. We have introduced that with the vision of selecting the most appropriate algorithm for a problem. For such a task, the type of variable is useful.
However, such a feature does not have any priority. I also think that defining it as of right now does not hurt.

I have added it to the `Problem.__init__ ` method and added a docstring comment. Thanks for letting us know!
