### ISSUE TITLE
MOO - Result returning variables & objective function in a 2 D array of shape n_population x n_var

### ISSUE THREAD

**Issue by arun-prakash-j-k** [anyoptimization/pymoo#187]
Hi, tried running the following sample code from your documentation on MOO, instead of getting a single list of X variables and single list of Objective Function value, I am getting a 2D array. Below is the code I have used.

  `import numpy as np
  from pymoo.core.problem import ElementwiseProblem
  
  class MyProblem(ElementwiseProblem):
  
      def __init__(self):
          super().__init__(n_var=2,
                           n_obj=2,
                           n_constr=2,
                           xl=np.array([-2,-2]),
                           xu=np.array([2,2]))
  
      def _evaluate(self, x, out, *args, **kwargs):
          f1 = 100 * (x[0]**2 + x[1]**2)
          f2 = (x[0]-1)**2 + x[1]**2
  
          g1 = 2*(x[0]-0.1) * (x[0]-0.9) / 0.18
          g2 = - 20*(x[0]-0.4) * (x[0]-0.6) / 4.8
  
          out["F"] = [f1, f2]
          out["G"] = [g1, g2]
  
  problem = MyProblem()
  
  from pymoo.algorithms.moo.nsga2 import NSGA2
  from pymoo.factory import get_sampling, get_crossover, get_mutation
  
  algorithm = NSGA2(
      pop_size=40,
      n_offsprings=10,
      sampling=get_sampling("real_random"),
      crossover=get_crossover("real_sbx", prob=0.9, eta=15),
      mutation=get_mutation("real_pm", eta=20),
      eliminate_duplicates=True
  )
  
  from pymoo.factory import get_termination
  
  termination = get_termination("n_gen", 40)
  
  from pymoo.optimize import minimize
  
  res = minimize(problem,
                 algorithm,
                 termination,
                 seed=1,
                 save_history=False,
                 verbose=False)
  
  X = res.X
  F = res.F
  print("Best solution found: \nX = %s\nF = %s" % (res.X.astype(int), res.F))`

And below are the results
_Best solution found: 
X = [[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
F = [[1.33777950e+00 7.83176782e-01]
 [7.49722343e+01 1.80917953e-02]
 [3.70090453e+01 1.65245338e-01]
 [1.59772304e+01 3.67434224e-01]
 [2.75433130e+00 7.17173694e-01]
 [3.85695705e+00 6.51700984e-01]
 [5.43505331e+00 6.04183995e-01]
 [6.37015084e+00 5.62155296e-01]
 [1.20702397e+01 4.25964612e-01]
 [5.18540004e+01 7.83551559e-02]
 [1.07935918e+01 4.61848532e-01]
 [7.10406068e+01 2.60131655e-02]
 [7.30276970e+00 5.42694093e-01]
 [6.16492618e+01 4.64117085e-02]
 [4.93555405e+01 8.86513322e-02]
 [8.72871259e+00 4.98860929e-01]
 [8.35897239e+00 5.18018440e-01]
 [9.87783586e+00 4.72430621e-01]
 [4.40623888e+01 1.13355505e-01]
 [3.88115154e+01 1.47843920e-01]
 [6.52538731e+01 3.70591049e-02]
 [4.32805943e+01 1.22448782e-01]
 [4.68201561e+01 1.01330088e-01]
 [4.05308005e+01 1.32181335e-01]
 [1.34388123e+01 4.11338836e-01]
 [1.46890691e+01 3.80949682e-01]
 [5.61228212e+01 6.44415510e-02]
 [1.86508504e+00 7.53947141e-01]
 [6.31774695e+01 4.33147569e-02]
 [4.39852133e+00 6.28247039e-01]
 [5.86364125e+01 5.96996956e-02]
 [2.11319599e+00 7.38315234e-01]
 [1.39340678e+01 3.95602495e-01]
 [5.42123732e+01 6.96718904e-02]
 [4.77250188e+01 9.71835682e-02]
 [6.95836576e+01 3.00581296e-02]
 [1.60394639e+00 7.80756111e-01]
 [3.97927791e+01 1.38060202e-01]
 [6.74946795e+01 3.20685135e-02]
 [5.85221106e+01 6.00548187e-02]]_

**Comment by julesy89** [comment]
The output is as expected. The `res.X` is a 2D matrix where each row represents a solution (sol x problem.n_dim) and the objectives `res.F` is a 2D matrix (sol x problem.n_obj). If you plot the solutions you see it is the right result.

```

import numpy as np

from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.core.problem import ElementwiseProblem
from pymoo.factory import get_sampling, get_crossover, get_mutation
from pymoo.factory import get_termination
from pymoo.optimize import minimize
from pymoo.visualization.scatter import Scatter


class MyProblem(ElementwiseProblem):

    def __init__(self):
        super().__init__(n_var=2,
                         n_obj=2,
                         n_constr=2,
                         xl=np.array([-2, -2]),
                         xu=np.array([2, 2]))

    def _evaluate(self, x, out, *args, **kwargs):
        f1 = 100 * (x[0] ** 2 + x[1] ** 2)
        f2 = (x[0] - 1) ** 2 + x[1] ** 2

        g1 = 2 * (x[0] - 0.1) * (x[0] - 0.9) / 0.18
        g2 = - 20 * (x[0] - 0.4) * (x[0] - 0.6) / 4.8

        out["F"] = [f1, f2]
        out["G"] = [g1, g2]


problem = MyProblem()


algorithm = NSGA2(
    pop_size=40,
    n_offsprings=10,
    sampling=get_sampling("real_random"),
    crossover=get_crossover("real_sbx", prob=0.9, eta=15),
    mutation=get_mutation("real_pm", eta=20),
    eliminate_duplicates=True
)

termination = get_termination("n_gen", 40)

res = minimize(problem,
               algorithm,
               termination,
               seed=1,
               save_history=False,
               verbose=False)

print("Best solution found: \nX = %s" % (res.X))


plot = Scatter()
plot.add(problem.pareto_front(), plot_type="line", color="black", alpha=0.7)
plot.add(res.F, facecolor="none", edgecolor="red")
plot.show()

```

**Comment by arun-prakash-j-k** [comment]
Okay, I am trying to solve a sample binary variable problem, where I need to select the maximum shortage value for various materials and I have to minimize the sum of all those maximum shortages across all the materials. Can you please check my code and let me know how to infer the output. `import numpy as np

from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.core.problem import ElementwiseProblem
from pymoo.factory import get_sampling, get_crossover, get_mutation
from pymoo.factory import get_termination
from pymoo.optimize import minimize
from pymoo.visualization.scatter import Scatter


class MyProblem(ElementwiseProblem):

    def __init__(self):
        super().__init__(n_var=4, 
                         n_obj=3, 
                         n_constr=2,
                         xl=anp.array([0,0,0,0]), #0
                         xu=anp.array([1,1,1,1]), # 1,#anp.array([1,1,1,1]),
                         type_var=bool
                        )
        
    def _evaluate(self, X, out, *args, **kwargs):
        f1 = -(X[0]*130 + X[1]*120) # max shortage for fg1
        f2 = -(X[2]*70 + X[3]*90) # max shortage for fg2
        f3 = -(f1+f2) # minimum shortage cost at overall
        g1 = ((X[0] + X[1]) - 1)**2 # select one comp for fg1
        g2 = ((X[2] + X[3]) - 1)**2 # select one comp for fg2
        out["F"] = anp.column_stack([f1,f2,f3])
        out["G"] = anp.column_stack([g1,g2]) #anp.column_stack([g1,g2]) 


problem = MyProblem()


algorithm = NSGA2(
    pop_size=40,
    n_offsprings=10,
    sampling=get_sampling("bin_random"),
    crossover=get_crossover("bin_two_point"),
    mutation=get_mutation("bin_bitflip"),
    eliminate_duplicates=True
)

termination = get_termination("n_gen", 40)

res = minimize(problem,
               algorithm,
               termination,
               seed=1,
               save_history=False,
               verbose=False)

print("Best solution found: \nX = %s" % (res.X.astype(int)))
print("Best solution found: \nF = %s" % (res.F))


plot = Scatter()
plot.add(problem.pareto_front(), plot_type="line", color="black", alpha=0.7)
plot.add(res.F, facecolor="none", edgecolor="red")
plot.show()`

**Comment by julesy89** [comment]
why would you choose exactly that solution? 

You are defining a three-objective problem and all solutions are indifferent to each other. Is there maybe anything else the algorithm shall consider?

**Comment by arun-prakash-j-k** [comment]
I need to get the maximum value out of the two variables in each of the first two objective function, also at the same time have to minimize the 3rd objective function.

**Comment by julesy89** [comment]
So why not redefining your problem to have two objectives: `np.max(f[:2])` will be `f1` then and `f[:,3]` be f2. 
If the new objectives are conflicting, you will still get a non-dominated set of solutions.

**Comment by arun-prakash-j-k** [comment]
Thanks, Julian. It worked :)

**Comment by julesy89** [comment]
Great! Glad to help.
