### ISSUE TITLE
Doubt on Hypervolume calculation

### ISSUE THREAD

**Issue by DTKx** [anyoptimization/pymoo#188]
Hello!
I was studying the pymoo implementation of the hypervolume for a bi-objective problem, however I could not understand a point and I was hoping you could please help me to understand what I am missing.

1. How would one normalize the hypervolume calculated by pymoo?
Example the code below prints the value 8, initially what I thought was to divide it by the total area=7*8.5=59.5 therefore a normalized hypervolume (norm_hv)= 0.13
```
ref_point = np.array([7, 8.5])
points = np.array([[6, 6.5], [5, 7], [4, 6.5], [3, 7.5], [2, 7.5]])
hv = get_performance_indicator("hv", ref_point=ref_point)
print("hv", hv.do(points))
```
However as I tried calculating the example by hand I found different area value of 17(norm_hv)= 0.28).
![image](https://user-images.githubusercontent.com/63344441/134811602-c0567977-d615-4482-a1ed-e225ba335829.png)

I have verified the code and from what I understood for the calculation the relevant points are subtracted by the reference point therefore I assume I should not use the total area(59.5) for normalization in the case of the pymoo hv calculation. Therefore the question, how would one normalize the volume provided by pymoo?

**Comment by julesy89** [comment]
HV by default does not do any normalization.

<img width="812" alt="Screen Shot 2021-10-01 at 8 15 50 AM" src="https://user-images.githubusercontent.com/10279009/135618357-b1837688-ab92-498d-b5e2-be8ff68d4f98.png">

This is how the `8.0` comes up. If we first normalize the points itself to lie between 0 and 1 and then apply the HV metric, we could do something like this:

```
import numpy as np

from pymoo.factory import get_performance_indicator
from pymoo.util.normalization import normalize

P = np.array([[6, 6.5], [5, 7], [4, 6.5], [3, 7.5], [2, 7.5]])

estm_ideal = P.min(axis=0)
estm_nadir = P.max(axis=0)

Pp = normalize(P, estm_ideal, estm_nadir)
ref_points = np.array([1.1, 1.1])

import matplotlib.pyplot as plt

plt.scatter(Pp[:, 0], Pp[:, 1])
plt.scatter(ref_points[0], ref_points[1], color="red", marker="x")
plt.show()

hv = get_performance_indicator("hv", ref_point=ref_points)

print("hv", hv.do(Pp))

```

Of course the estimate ideal and nadir points could also be the real ones if the pf is known.  Then we calculate the hv in the following space:

<img width="583" alt="Screen Shot 2021-10-01 at 8 19 59 AM" src="https://user-images.githubusercontent.com/10279009/135618818-04e8fcd9-2b99-403b-9f5a-82a56281544f.png">


Is this what you meant?

**Comment by DTKx** [comment]
Hello @Julesy89!
thank you for the detailed answer. That is exactly my doubt you saved me. I understood, your approach is much simpler than I was expecting.

Thank you very much again!
