### ISSUE TITLE
 '<=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by pmdevcode** [anyoptimization/pymoo#189]
Hi, 

I have tried many different algorithms and I have the same issue after 20-30 iterations. 

The value of out["CV"] is None

Here is my code:

`
problem = XXXProblem(runner=pool.starmap, func_eval=starmap_parallelized_eval)
algorithm = ISRES(n_offsprings=200, rule=1.0 / 7.0, gamma=0.85, alpha=0.2)

res = minimize(problem, algorithm, seed=1, n_gen=2)
log('Threads:', res.exec_time)`

`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8956/3690139351.py in <module>
      6 clean_resources() #wyzyscic zasoby
      7 
----> 8 run() #optymalizacja
      9 
     10 disconnect_from_server()

~\AppData\Local\Temp/ipykernel_8956/3558226086.py in run()
    111     algorithm = ISRES(n_offsprings=200, rule=1.0 / 7.0, gamma=0.85, alpha=0.2)
    112 
--> 113     res = minimize(problem, algorithm, seed=1, n_gen=2)
    114     log('Threads:', res.exec_time)
    115     pool.close()

C:\ProgramData\Anaconda3\envs\...\lib\site-packages\pymoo\optimize.py in minimize(problem, algorithm, termination, copy_algorithm, copy_termination, **kwargs)
     81 
     82     # actually execute the algorithm
---> 83     res = algorithm.run()
     84 
     85     # store the deep copied algorithm in the result object

C:\ProgramData\Anaconda3\envs\...\lib\site-packages\pymoo\core\algorithm.py in run(self)
    211         # while termination criterion not fulfilled
    212         while self.has_next():
--> 213             self.next()
    214 
    215         # create the result object to be returned

C:\ProgramData\Anaconda3\envs\...\lib\site-packages\pymoo\core\algorithm.py in next(self)
    231         # call the advance with them after evaluation
    232         if infills is not None:
--> 233             self.evaluator.eval(self.problem, infills, algorithm=self)
    234             self.advance(infills=infills)
    235 

C:\ProgramData\Anaconda3\envs\...\lib\site-packages\pymoo\core\evaluator.py in eval(self, problem, pop, skip_already_evaluated, evaluate_values_of, count_evals, **kwargs)
     93         # actually evaluate all solutions using the function that can be overwritten
     94         if len(I) > 0:
---> 95             self._eval(problem, pop[I], evaluate_values_of=evaluate_values_of, **kwargs)
     96 
     97             # set the feasibility attribute if cv exists

C:\ProgramData\Anaconda3\envs\...\lib\site-packages\pymoo\core\evaluator.py in _eval(self, problem, pop, evaluate_values_of, **kwargs)
    110         evaluate_values_of = self.evaluate_values_of if evaluate_values_of is None else evaluate_values_of
    111 
--> 112         out = problem.evaluate(pop.get("X"),
    113                                return_values_of=evaluate_values_of,
    114                                return_as_dictionary=True,

C:\ProgramData\Anaconda3\envs\....\lib\site-packages\pymoo\core\problem.py in evaluate(self, X, return_values_of, return_as_dictionary, *args, **kwargs)
    142             out["CV"] = CV
    143             print(out["CV"])
--> 144             out["feasible"] = CV <= 0
    145 
    146         # in case the input had only one dimension, then remove always the first dimension from each output

TypeError: '<=' not supported between instances of 'NoneType' and 'int' `

**Comment by julesy89** [comment]
Does it work without parallelization?

Does  `problem.eval(X)` return the correct values?
