### ISSUE TITLE
Feature Request: separate method for objective and constraint evaluation

### ISSUE THREAD

**Issue by stklik** [anyoptimization/pymoo#195]
We are using pymoo for the evaluation of noisy systems and are using pymoo's test problems as "controlled benchmarks" where we inject noise ourselves.
However, we are running into a conceptual problem that we would like to address in the future.

Currently our "add-noise" routine is basically a wrapper that calls the actual problem's `_evaluate` method, and then adds a certain stochastic noise to the objective and constraint values.  
Conceptually:  
`Problem._evaluate(...) -> (objs, consts)` and we then do   
`NoiseWrapper._evaluate(...) -> add_noise(objs), add_noise(consts)`
For the moment, this works fine as initial approximation.

However, given that the constraints are typically calculated based on the objectives, it would be nicer if we could somehow recalculate the constraint-values on the noisy-objectives. I.e. something like  
`NoiseWrapper._evaluate(...) -> add_noise(objs), calc_constraints(noisy_objectives)`. (`noisy_objectives` are the values calculated by the `add_noise(objs)` argument...)

I was wondering if this is something that might be added in general in the Framework, such that for constrained problems, the constraint calculation is not done in `_evaluate(...)` but in a subroutine `_evaluate_constraints(..., calculated_objectives)`.

I hope this description is somewhat understandable...
- - -
Upsides:
- pymoo's `_evaluate` method is more structured
- all existing code will continue working without problem, since one can choose if and when to call `_evaluate_constraints(...)`
- our benchmarks are conceptually more representative

Downsides:
- Minimal restructuring (e.g. adding a `_evaluate_constraints` stub in the base-Problem class)
- Practical Effort: the constrained test problems should gradually be adapted to this system (should be somewhat trivial, I believe)

**Comment by stklik** [comment]
Hi, sorry for the late reply. Submission deadline came up.

> Is that construct an option for you?

I believe this solution works for us. 


Regarding implementation of algorithms: we are currently working on techniques to improve existing algorithms using our technique. I'm not sure if we have the necessary resources to work other parts at the moment. 
(However, if things go well, we maybe need to work on implementation of such "competitors" in a little while 🤞 )

**Comment by julesy89** [comment]
Glad that this solution works for you.

Sounds great!
