### ISSUE TITLE
Documentation for previous version

### ISSUE THREAD

**Issue by Atulsingh92** [anyoptimization/pymoo#196]
Hello Julian, 

I am using 0.4.2.2, and running some of the current examples (0.5), keep throwing lots of errors, which I assume , would not happen if the examples were from previous versions. (Case in point, I am looking for a mixed variable example for the previous version)

Would it be possible to also have the documentation of the previous version in place?

**Comment by dbrizard** [comment]
I tried to access documentation of version 0.5.0 (last is 0.6.0), but `archive.pymoo.org` is asking me a username and a password.
Am I missing something?

**Comment by blankjul** [comment]
Checkout the link again: https://pymoo.org/versions.html
The credentials are mentioned at the very top of the page.

We have this to prevent search engines from crawling old pages.

**Comment by dbrizard** [comment]
@blankjul thank you very much for the quick answer. 
I am sorry I overlooked the first lines of the documentation.

**Comment by blankjul** [comment]
You are welcome!
