### ISSUE TITLE
Discrete sampling in multiples of two.

### ISSUE THREAD

**Issue by Atulsingh92** [anyoptimization/pymoo#197]
Hello Julian, 

I had a question about sampling the discrete variable problem only in multiples of a number. This is becuase I am trying to solve a heat exchanger problem, which has "number of passes", basically the the flow of fluid going form one pass to another, before it exits the system. Essentially, this variable cannot be odd for the design I am working on. 

```
def __init__(self):
        super().__init__(n_var = 4,
                         n_obj = 1,
                         n_constr = 5,             
                         xl = anp.array([26, 17, 2, 525]), # Number of pass is 2<Np<8, and 2, 4, 6, 8 are only permissible
                         xu = anp.array([32, 34, 8, 788]),
                         )
```
Ofcourse, the best result right now comes with 3 number of passes!
Any suggestions on how can I set this up?

**Comment by Atulsingh92** [comment]
Well, like I mentioned, only even number are permissible. 
So, needed 2, 4, 6, 8 instead!

**Comment by julesy89** [comment]
You do! Because
1 -> 2, 
2 -> 4, 
3 -> 6, 
4 -> 8

It is just a simple remapping.
