### ISSUE TITLE
how can I print the hypervolume for each generation？

### ISSUE THREAD

**Issue by lmx-HUST** [anyoptimization/pymoo#201]
Hello,
I want to use hypervolume to evaluate if the optimization process has been convergence. From this version of pymoo documentation: 
https://www.pymoo.org/getting_started.html#Functional-Interface
It seems like I can get  hypervolume for each generation directly by turning 'verbose' true.

But now i only get the following parameters instead:

n_gen |  n_eval |   cv (min)   |   cv (avg)   |  n_nds  |     eps      |  indicator  

May you explain what 'eps' and 'indicator' mean? Can I test the convergence from them? If not how can I test the convergence?

Thanks!

**Comment by lmx-HUST** [comment]
Find more detailed explanation about how to terminate optimization here,
https://www.pymoo.org/interface/termination.html
think I figure out this problem.

**Comment by julesy89** [comment]
Yes, the eps and indicator values are used for termination. For me details please have a look at our paper: 
https://www.egr.msu.edu/~kdeb/papers/c2020003.pdf

For an HV tutorial the getting started guide part IV might be helpful:
https://pymoo.org/getting_started/part_4.html

**Comment by lmx-HUST** [comment]
Thank you!

> Yes, the eps and indicator values are used for termination. For me details please have a look at our paper: https://www.egr.msu.edu/~kdeb/papers/c2020003.pdf
> 
> For an HV tutorial the getting started guide part IV might be helpful: https://pymoo.org/getting_started/part_4.html
