### ISSUE TITLE
Adding/Modifying custom point (Individual) for the Population (NSGA2 or any other MOO)

### ISSUE THREAD

**Issue by padmassun** [anyoptimization/pymoo#202]
Hello,

I would like to add my own point or replace an existing point with my own, to an existing population.

I have implemented the current code. Is my implementation correct? Or is there a better way to do this? Would this cause any problem?

If I specify `eliminate_duplicates=True` for the `NSGA2` algorithm, and the custom point is already evaluated in a previous generation, would it cause any Issues? (In the actual code, most of my variables are discrete variables, and I'm performing a Mixed variable problem).

Thank you.

Modified from source: https://pymoo.org/algorithms/usage.html#Problem-Depdendent
```python
import pprint as pp

import numpy as np
import datetime

from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.factory import get_problem
from pymoo.optimize import minimize
from pymoo.core.evaluator import Evaluator
problem = get_problem("zdt1")

algorithm = NSGA2(pop_size=100)

# prepare the algorithm to solve the specific problem (same arguments as for the minimize function)
algorithm.setup(problem, ('n_gen', 10), seed=1, verbose=False)

# until the algorithm has no terminated
while algorithm.has_next():

    # ask the algorithm for the next solution to be evaluated
    pop = algorithm.ask()

    # an example of a custom function
    custom_point = np.random.rand(30)
    # pp.pprint(custom_point)
    for indx, indiv in enumerate(pop):
        if indx == 0:
            # pp.pprint(indiv.__dict__)
            indiv.X = custom_point
            # pp.pprint(indiv.__dict__)
            exit()

    # pp.pprint(pop)

    # evaluate the individuals using the algorithm's evaluator (necessary to count evaluations for termination)
    algorithm.evaluator.eval(problem, pop)

    # returned the evaluated individuals which have been evaluated or even modified
    algorithm.tell(infills=pop)

    # do same more things, printing, logging, storing or even modifying the algorithm object
    print(algorithm.n_gen, algorithm.evaluator.n_eval)


# obtain the result objective from the algorithm
res = algorithm.result()

# calculate a hash to show that all executions end with the same result
print("hash", res.F.sum())
```

**Comment by julesy89** [comment]
Yes, your code injects a random point in each iteration. The `exit()` is not necessary, though. 

If the solution is already in the population, it will be added twice, but depending on the algorithm, be eliminated in the `advance` function. But it all depends on your ultimate goal or, in other words, what you are trying to achieve with external solution injections.

**Comment by padmassun** [comment]
Thank you.
