### ISSUE TITLE
Differential Evolution - Jitter not working, and changes in bounds repair.

### ISSUE THREAD

**Issue by bruscalia** [anyoptimization/pymoo#226]
Dear Mr. Blank and pymoo contributors,

Once again, thank you for the amazing library. I would like to warn you about a conceptual problem with jitter though. The main idea of jitter is to add random rotation in the difference vector of DE by multiplying each individual component (variable) by a random factor (centered in one). For it to be possible, jitter should generate random multipliers with shape (n_matings, n_var) in DEX, so that each individual component of the differential vectors for each mating has a corresponding random value.

Moreover, the current method for repair of mutant vectors out of bounds is great, but it does not correspond to random initialization. By the equation of repair_random_init, I believe it is currently working as a bounce back method. I remind you that if adopting the changes in issue #224 the base vector for bounce back should be Xr0, probably parent of index P[:, 1].

For more details on these topics I suggest you to check the book Differential Evolution: A Practical Approach to Global Optimization by Price et al. (2005).

Kind regards,

Bruno Scalia

**Comment by julesy89** [comment]
Hi Bruno,

thank you very much for your feedback. I have recently completely reimplemented DE (not pushed to Github yet).
Do you like to have a discussion via Zoom about DE and its variants? 
The implementation was based on a rather simple MATLAB version I have found and does not really have newer features.

**Comment by bruscalia** [comment]
Hi @julesy89 ,

I would be very happy to have an opportunity of discussing DE with you. I'm actually quite unfamiliar with github communication, so I'm afraid I might lose some messages. Would you mind if we schedule this via e-mail? You can reach out to me at bruscalia12@gmail.com.

Please feel free to suggest anytime you would be available.

My kind regards,

Bruno Scalia
