### ISSUE TITLE
Integration with OpenAI Gym to support a wider set of problems and reinforcement learning algorithms

### ISSUE THREAD

**Issue by smartsystems4u** [anyoptimization/pymoo#229]
I'd love to see integration with https://gym.openai.com/ to extend pymoo to many more problems and make integration of new algorithms especially reinforcement learning easier.

Is this interesting to you and is it feasible?

**Comment by julesy89** [comment]
It is 100% feasible and would be interesting! If you intend to work on it let me know. 
I can help you to get started and would also put up a tutorial on how to run the `gym` problems in the documentation.
