### ISSUE TITLE
Reference vectors that incorporate preferred subspace

### ISSUE THREAD

**Issue by BenConstable9** [anyoptimization/pymoo#230]
Thank you for this great library. I am trying to perform optimisation using RVEA that incorporates Preference Articulation. I have a set of reference points and as noted in the original paper, need to generate a set of reference direction vectors that are within the search space. 

I cannot see a way to do this in Pymoo currently. Is there any chance of this being supported?

**Comment by julesy89** [comment]
You are probably already are that pymoo has RNSGA3, which supports reference points too.

The next release of pymoo will have an implementation of RVEA.
You can have a sneak peek here: https://github.com/anyoptimization/pymoo/blob/master/pymoo/algorithms/moo/rvea.py

There, you can also find the transformation of the reference directions.

**Comment by BenConstable9** [comment]
Great thank you for this.

I've taken a look so if I transform a set of uniform reference vectors to a subspace of the search space and set the adaption frequency to None, then this should work?

**Comment by julesy89** [comment]
It might be better simply to use the method directly.

```
self.V = calc_V(calc_V(self.ref_dirs) * (self.nadir - self.ideal))
self.gamma = calc_gamma(self.V)
```

You will also have to pull or the other two helper methods.

AND the adaption does not happen in the search but in objective space!
Most MOO algorithms normalize the objective space and then apply reference directions in the unit space.
In RVEA, the objective space is kept unmodified, but the reference directions are re-scaled. Both are valid approaches.

**Comment by BenConstable9** [comment]
Thank you.

I've used the following code to transform as per the published paper on RVEA. Are you suggesting I need to adjust the V and gamma as well? 

`def transform_vector() : return (np.add(np.dot(RADIUS, vector), np.dot((1 - RADIUS), CENTRAL))) / (np.linalg.norm(np.add(np.dot(RADIUS, vector), np.dot((1 - RADIUS), CENTRAL))))`

I've done an approach like this:

`ref_dirs = get_reference_directions(
            "das-dennis", NUMBER_OBJECTIVES, n_partitions=PARTITIONS)

        new_ref_dirs = []
        for ref in ref_dirs:
            new_ref_dirs.append(transform_vector(
                ref, RADIUS, ACHIEVABLE_REFERENCE_POINT[0]))

        new_ref_dirs = np.array(new_ref_dirs)

        # Get Algorithm
        algorithm = RVEA(
            new_ref_dirs,
            pop_size=POP_SIZE,
            alpha=ALPHA,
            adapt_freq=None,
            selection=RandomSelection(),
            crossover=SimulatedBinaryCrossover(
                eta=SBX_ETA, prob=SBX_PROB),
            mutation=PolynomialMutation(
                eta=PM_ETA, prob=PM_PROB), n_offsprings=None)

        res = minimize(problem,
                       algorithm,
                       save_history=True,
                       termination=('n_gen', 500),
                       pf=pf,
                       disp=False)`

**Comment by julesy89** [comment]
Reference directions usually sum up to 1. However, for the transform in RVEA they are first transformed to have a norm of one
```
def calc_V(ref_dirs):
    return ref_dirs / np.linalg.norm(ref_dirs, axis=1)[:, None]
```

Then the resulting values are rescaled (using ideal and nadir point) and again be normalized to have a norm of one.

```
V = calc_V(calc_V(self.ref_dirs) * (self.nadir - self.ideal))
```

Since this changes `V` also the angles `gamma` need to be recalculated.
