### ISSUE TITLE
Checkpoint creation error

### ISSUE THREAD

**Issue by m-zakeri** [anyoptimization/pymoo#231]
Hi, 
I get the following error when trying to make a checkpoint for my algorithm: 

`AttributeError: Can't pickle local object 'ElementwiseDuplicateElimination.__init__.<locals>.<lambda>`

My script contains the following statements:

```Python
res = minimize(problem=problems[2],
                   algorithm=algorithms[2],
                   termination=my_termination,
                   seed=1,
                   verbose=True,
                   copy_algorithm=True,
                   copy_termination=True,
                   save_history=False,
                   )
np.save('checkpoint', res.algorithm)
```

**Comment by julesy89** [comment]
I quickly had a look and the `ElementwiseDuplicateElimination` uses a lambda function that can not be pickled.
What algorithm are you executing?

**Comment by m-zakeri** [comment]
> 

I am executing an instance of NSGA-III.

**Comment by julesy89** [comment]
Okay. You are passing your own Duplicate Elimination which has a lambda function. Eliminate the lambda function and copy it out of the class and it shall work.

**Comment by m-zakeri** [comment]
> Okay. You are passing your own Duplicate Elimination which has a lambda function. Eliminate the lambda function and copy it out of the class and it shall work.

Ok! Thanks. I will put a feedback here.
