### ISSUE TITLE
MixedVariableSampling does not work with NelderMead (max_alpha)

### ISSUE THREAD

**Issue by cristianmatache** [anyoptimization/pymoo#236]
I think I found an issue when using `NelderMead` with `MixedVariableSampling`. Let's say we have one integer and one real parameter. We could write something like this:
```python
sampling= MixedVariableSampling(
    ["a", "b"], {"a": get_sampling("int_random"), "b": get_sampling("real_random")}
)
```
these samples are combined internally in the `concatenate_mixed_variables` function. This function combines them in a new ndarray with the `np.object` dtype. 

NelderMead calls `max_alpha` (in `vectors.py`), there pymoo check `np.isnan(val)` but `val`'s dtype is `np.object` and the check fails.

**Comment by cristianmatache** [comment]
Similar issues would also occur in `numeric.py` for `isfinite` checks

**Comment by julesy89** [comment]
Thanks for using pymoo! `NelderMead` ONLY works for continuous variables (by the design of the algorithm).
Does `GA` work for you?
