### ISSUE TITLE
If with a constant

### ISSUE THREAD

**Issue by LFBJC** [anyoptimization/pymoo#248]
This is a simple problem, but there may be other lines in the code with the same issue. One line draw my attention on the file https://github.com/anyoptimization/pymoo/blob/master/pymoo/operators/mutation/inversion.py
seq = seq if not None else random_sequence(len(y))

well, None is a constant and it's boolean value is always False, so it is equivalent to:
seq = seq

I think it is supposed to be:
seq = seq if seq is not None else random_sequence(len(y))

**Comment by julesy89** [comment]
It will be fixed in the next version. thank you for reporting this issue!
