### ISSUE TITLE
How to use pymoo deal with cutting stock probelm?

### ISSUE THREAD

**Issue by kunyaoli** [anyoptimization/pymoo#256]
There are 100 steel pipes of 10m length, which need to be cut into 30 pipes of 3.4m, 40 pipes of 4.1m and 50 pipes of 5.2m. How to cut the least of the waste?

**Comment by julesy89** [comment]
Hi Kunyaoli,

this is by far not enough information to solve your problem. I recommend first writing down the mathematical formulation.
Then, please check out our getting started guide (https://pymoo.org/getting_started/index.html) for more information about the implementation of a problem.
