### ISSUE TITLE
Since Numpy 1.20, `np.int` is deprecated. Can be replaced by `np.int_`, `np.int32`, `np.int64`, or `np.intp`

### ISSUE THREAD

**Issue by Jrmy-rbr** [anyoptimization/pymoo#257]
Hello,

In this code, `np.int` is used. It causes a deprecated warning for people using numpy>=1.20.

`np.int` can be replaced by either, `np.int_`, `np.int32`, `np.int64`, or `np.intp`

https://github.com/anyoptimization/pymoo/blob/c6426a721d95c932ae6dbb610e09b6c1b0e13594/pymoo/algorithms/moo/age.py#L93-L96

**Comment by julesy89** [comment]
Thanks for letting me know. I have already fixed that in the majority of the framework. I apparently have missed `AGE`. 
It will be fixed in the new version!
