### ISSUE TITLE
Population Set Attribute Error: Number of values and population size do not match!

### ISSUE THREAD

**Issue by MehwishNaz007** [anyoptimization/pymoo#265]
I am facing the above mentioned error while executing a single objective GA for optimization using pymoo
Following is the problem
class CalculateFitness(Problem):
    def _evaluate(self, size, out, *args, **kwargs):
           weight, chrom_len1 = g.showDegree()
          rankedfitness = rankfitness()
        out['F'] = np.array(rankedfitness)
        print("out = ",out['F'])
        return out
problem = CalculateFitness(n_var=20, n_obj=1, n_constraint=0)
print(problem)
Note: My initial population size is [50](`url`)
![Picture1](https://user-images.githubusercontent.com/102521371/160388664-391fd23d-6436-4814-9c6d-62d5c46c526c.png)

**Comment by julesy89** [comment]
That error indicates that you are not returning or setting the right shape to `out["F"]` or `out["G"]`.
Please have another look at the getting started guide regarding what shape of outputs should be set.

https://pymoo.org/getting_started/part_2.html

For more information about the correct definition of a test problem please have a look here:
https://pymoo.org/problems/definition.html

**Comment by MehwishNaz007** [comment]
Waiting for the response. If you please get me out from this issue. I am not getting help from the above mentioned links as i have gone through them thoroughly.

**Comment by julesy89** [comment]
Were you able to resolve the issue meanwhile?

Feel free to post code that I can run to reproduce the error.
