### ISSUE TITLE
Upgrade pymoo to support Python 3.10 and numpy 1.20

### ISSUE THREAD

**Issue by Immudzen** [anyoptimization/pymoo#268]
Right now pymoo does not support Python > 3.9 or newer version of numpy and changes needed to make it compatible are pretty simple. Using the newest version of cma enables pymoo to be compatible with 3.10 and changed np.int -> int and np.bool -> bool fixes the numpy issue. I am also submitting a pull request to fix this issue. 

I have also run all the unit tests and everything passed.

**Comment by julesy89** [comment]
The new release will support Python 3.10 and also update the new CMA version. Check out the development branch for a sneak peak.
