### ISSUE TITLE
Customizing bounds for my optimization problem.

### ISSUE THREAD

**Issue by DDLade97** [anyoptimization/pymoo#271]
Hello, I am using pymoo to work on my MOO problem. I am working on placing Acess points of WiFi and LiFi in a room. Initially, I was keeping it to square or rectangular rooms for placement. Now I am thinking of extending this to irregularly shaped rooms. But I am not sure how to modify my problem bounds and then use a custom type variable for it because the AP placement is outside the room dimension. Is there a way to describe specific x and y boundary coordinates for the optimization for placement within that only?
I have attached an image for reference as to how the placement now happens.
![image](https://user-images.githubusercontent.com/93923187/163716128-ac3a32f7-12f5-4ec9-a7a8-f11729323988.png)

**Comment by julesy89** [comment]
The bounds, in general, define a rectangular shape. Suppose you need to define a different shape for the area. In that case, you can define the rectangle to be the bounding box (largest possible values for each coordinate) and then constraints (which can also cover dependencies along with variables) to further constrict the space.

The getting started guide demonstrates how constraints can be added to a problem:
https://pymoo.org/getting_started/part_1.html
