### ISSUE TITLE
Problem when instantiating CTP multimodal problems

### ISSUE THREAD

**Issue by mooscaliaproject** [anyoptimization/pymoo#277]
https://github.com/anyoptimization/pymoo/blob/0496a3c6765826148d8bab21650736760517dd25/pymoo/problems/multi/ctp.py#L26

Hi, Julian! I hope you have been well over these last few months!

I am writing to inform you that I believe the definition of boundaries in the multimodal version of CTP should consider a 1d array rather than a 2d array.

I believe something like xu[1:] = 5.12 would solve it.

My kind regards,

Bruno Scalia

**Comment by julesy89** [comment]
Thanks for letting me know! I have just fixed it.

(Exactly what you have said should be the case)
