### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by tdubach** [anyoptimization/pymoo#280]
In the [documentation](https://pymoo.org/problems/many/dtlz.html#DTLZ2) under DTLZ2 there is a typo in the sentence:
Once again, the x vector is constructed with k=n−M+1 variables.
I believe it should instead be:
Once again, the x_M vector is constructed with k=n−M+1 variables.

cheers

**Comment by julesy89** [comment]
Fixed it. Thanks!
