### ISSUE TITLE
__init__() got an unexpected keyword argument 'runner'

### ISSUE THREAD

**Issue by licheng0794** [anyoptimization/pymoo#281]
I run the example in the link
https://pymoo.org/problems/parallelization.html

define the problem by passing the starmap interface of the thread pool
problem = MyProblem(runner=pool.starmap, func_eval=starmap_parallelized_eval)

And I got an error '__init__() got an unexpected keyword argument 'runner'

some suggestions?

**Comment by licheng0794** [comment]
from scipy.linalg import norm
from pymoo.core.problem import ElementwiseProblem
import numpy as np

targetoutflow = [1.929, 50.2, 7.254]

def testfunc(x):
    return [x[0]+x[2], x[2]+x[3], x[6]+x[7]]

class MyProblem(ElementwiseProblem):

    def __init__(self):
        super().__init__(n_var=16,
                         n_obj=3,
                         n_constr=2,
                         xl=np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.01, 0.35, 0.38, 0.2, 0.6, 0.02, 84, 0.05, 2.5]),
                         xu=np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.55, 0.5, 3, 0.75, 1.5, 13.2, 1.44, 360, 0.15, 4.5]), 
                         elementwise_evaluation=True, **kwargs)

    def _evaluate(self, x, out, *args, **kwargs):
        outflow = testfunc(x)
        f1 = (outflow[0] - targetoutflow[0]) ** 2
        f2 = (outflow[1] - targetoutflow[1]) ** 2
        f3 = (outflow[2] - targetoutflow[2]) ** 2
        g1 = (x[0] + x[1] + x[2] + x[3] - (totalinflow[1]-totalinflow[3])/totalinflow[1])**2 - 1e-3 
        g2 = ((x[4] + x[5] - (totalinflow[2] - totalinflow[4] - 0.08*(totalinflow[1]*x[2] + 0) - 0.06*(totalinflow[1]*x[1] + 0)) / totalinflow[2]))**2 - 1e-4

        out["F"] = [f1, f2, f3]
        out["G"] = [g1, g2]


from pymoo.core.problem import starmap_parallelized_eval
from multiprocessing.pool import ThreadPool

# the number of threads to be used
n_threads = 8

# initialize the pool
pool = ThreadPool(n_threads)

# define the problem by passing the starmap interface of the thread pool
problem = MyProblem(runner=pool.starmap, func_eval=starmap_parallelized_eval)


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_20712\2844169824.py in <module>
      4 pool = ThreadPool(n_threads)
      5 
----> 6 problem = MyProblem(runner=pool.starmap, func_eval=starmap_parallelized_eval)

TypeError: __init__() got an unexpected keyword argument 'runner'

**Comment by julesy89** [comment]
The problem is that the `kwargs` are not looped through. Redefine the problem as follows

```
class MyProblem(ElementwiseProblem):

    def __init__(self, **kwargs):
        super().__init__(n_var=16,
                         n_obj=3,
                         n_constr=2,
                         xl=np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.01, 0.35, 0.38, 0.2, 0.6, 0.02, 84, 0.05, 2.5]),
                         xu=np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.55, 0.5, 3, 0.75, 1.5, 13.2, 1.44, 360, 0.15, 4.5]), 
                         elementwise_evaluation=True, **kwargs)
```

and it should work. Please reopen the issue if not and I will have another look.
