### ISSUE TITLE
CMA-ES seed not working

### ISSUE THREAD

**Issue by 2ThomasAnd** [anyoptimization/pymoo#282]
## Description
Setting seed e.g. to 1 does not work, two runs do not give the same result.
Used Version: Python 3.9.12, numpy 1.22.3, pymoo 0.5.0

## Example Code
import numpy as np
from pymoo.algorithms.soo.nonconvex.cmaes import CMAES
from pymoo.factory import get_problem
from pymoo.optimize import minimize

problem = get_problem("sphere")
algorithm = CMAES()
res = minimize(problem, algorithm, ("n_eval", 50), seed=1, verbose=False)
print(res.F)

## Suggested solution
In the file cmaes.py line 378 change self.options['seed'] = seed to self.options['seed'] = self.seed (and in line 368 delete seed=None).
#

**Comment by julesy89** [comment]
Fixed! Thanks for letting us know.
