### ISSUE TITLE
Parallelize CMA-ES with joblib

### ISSUE THREAD

**Issue by 2ThomasAnd** [anyoptimization/pymoo#290]
### Description
Running minimize function with cma-es in parallel using joblib returns an KeyError 'es'
Used Versions: Python 3.9.12, numpy 1.23.0, pymoo 0.5.0, joblib 1.1.0

### Example Code
import numpy as np
from joblib import Parallel, delayed
from pymoo.algorithms.soo.nonconvex.cmaes import CMAES
from pymoo.factory import get_problem
from pymoo.optimize import minimize

problem = get_problem("sphere")
algorithm = CMAES()
results = Parallel(n_jobs=2)(delayed(minimize)(problem, algorithm, seed=s) for s in range(1, 3))
print([results[i].F for i in range(0, len(results))])

### Suggested solution
In the file cmaes.py line 446 change del state["es"] to state.pop("es", None)

**Comment by julesy89** [comment]
Thanks for letting us know! I have just fixed this one simple line. 
Please let me know if you find anything else that can be improved.
