### ISSUE TITLE
Make 3D-Scatter plot optional

### ISSUE THREAD

**Issue by schmoelder** [anyoptimization/pymoo#292]
Hey,
I'm using  pymoo for my process simulation package. This also includes the plotting methods, especially [Scatter](https://pymoo.org/visualization/scatter.html). 

While I understand that the 3D-plot is nice to have iff n_obj == 3, I'd like to keep things consistent in my case and prefer to always work on 2D-Scatter/Pareto grids. An additional flag (e.g. `plot_3D=False`) for either `Scatter.__init__()` or `plot.add()` would be great!

**Comment by blankjul** [comment]
As you have mentioned the `Scatter` plot is designed to always select the most convenient (at least in my opinion) plotting option.

==2D -> 2D Plot 
==3D -> 3D Plot
>4D   -> Pairwise

Do I understand your suggestion right to have a flag that plots 3D also as a pairwise plot?

**Comment by schmoelder** [comment]
That is correct. Often times, I find 3D Plots hard to read. And even the 2D-case is just a special case of a pairwise plot, so I'd like to keep it consistent.

**Comment by blankjul** [comment]
Please see my most recent commit. Thi shall resolve the issue.

**Comment by schmoelder** [comment]
Hey, thanks for implementing that so quickly! 
I just added it to my library and it works just fine! :)
