### ISSUE TITLE
Question: Dataset with categorical columns

### ISSUE THREAD

**Issue by abedshantti** [anyoptimization/pymoo#293]
What is the best of pre-processing tabular data with categorical columns such that it can be interpreted by pymoo and its algorithms? Based on what I can gather, the categorical features are to be one-hot encoded and a min-max scaler can be used for the real-valued columns. Do I need to set the one-hot encoded columns as integer valued-types and add a constraint entailing that the sum of these integer columns should be equal to 1, or is there another and a more systematic way of representing categorical features for multi-objective optimisation?

**Comment by blankjul** [comment]
Sorry for the late reply. Can you elaborate a little bit more if you are still facing the problem?

What is the exact problem you are trying to solve?
