### ISSUE TITLE
How to use custom individuals?

### ISSUE THREAD

**Issue by alfcan** [anyoptimization/pymoo#294]
Hi,
I have a problem with using individuals other than normal types such as array, int, string,.. In my case I use a tree object as an individual and I have already defined the custom operators.
I can't figure out how to customize the individual, how can I solve?

**Comment by blankjul** [comment]
Please checkout this guide: https://pymoo.org/customization/custom.html
This shows an example with a custom data type `object`. This can be in principle any type (also trees) you define your operators on.

**Comment by alfcan** [comment]
Greetings,
this library is really great, thank you.
I was able to solve the problem by following the guide you indicated.

Now I have run into a mistake:
"File "pymoo/cython/non_dominated_sorting.pyx", line 25, in pymoo.cython.non_dominated_sorting.fast_non_dominated_sort
ValueError: Buffer has wrong number of dimensions (expected 2, got 1)"
I believe it was caused by the custom operators, but I can't understand where the error came from.
