### ISSUE TITLE
Question: Access to initial population and its objective values

### ISSUE THREAD

**Issue by frodbej** [anyoptimization/pymoo#296]
Hi! I am using the pymoo NSGA3 algorithm to optimize multiple objectives. After the optimization, I can access the final population and the objective values for each individual of the population through the `Result` object to write them into a file, but I would also like to access the initial individuals and their objective values to write them into a file and check the changes that have led to the optimization of objectives. Can I somehow specify the algorithm to store the initial population for this purpose? Thanks in advance!

**Comment by blankjul** [comment]
Yes, you can!

I have designed pymoo to be very modular. There are two ways of storing intermediate results:

- Callback: https://pymoo.org/interface/callback.html
- Ask-And-Tell: https://pymoo.org/algorithms/usage.html#nb-algorithms-ask-and-tell

I hope this helps,
Julian
