### ISSUE TITLE
Implemetation of binary_tournament error

### ISSUE THREAD

**Issue by miko1ann** [anyoptimization/pymoo#300]
Hellow.
I tried to implement binary tournament in my code and I found error in sample:

Web [page](https://pymoo.org/operators/selection.html?highlight=binary%20tournament) containst the code:

```
def binary_tournament(pop, P, algorithm, **kwargs):

    #The P input defines the tournaments and competitors
    n_tournaments, n_competitors = P.shape

    if n_competitors != 2:
        raise Exception("Only pressure=2 allowed for binary tournament!")

    # the result this function returns
    import numpy as np
    S = np.full(n_tournaments, -1, dtype=np.int)

    # now do all the tournaments
    for i in range(n_tournaments):
        a, b = P[i]

        # if the first individiual is better, choose it
        if pop[a].F < pop[a].F:
            S[i] = a

        # otherwise take the other individual
        else:
            S[i] = b

    return S
```

The string 
`if pop[a].F < pop[a].F:`
should be 
`if pop[a].F < pop[b].F:`
if used minimization strategy

**Comment by blankjul** [comment]
Good catch! I have fixed it in the commit shown above.

Please let us know if you find anything else to keep the documentation as error-free as possible.
