### ISSUE TITLE
Issue with new release 0.6.0

### ISSUE THREAD

**Issue by Junaid199f** [anyoptimization/pymoo#301]
Hello, While using the new version of pymoo i faced this problem.

ImportError: cannot import name 'set_cv' from 'pymoo.core.evaluator' (/usr/local/lib/python3.7/dist-packages/pymoo/core/evaluator.py)

Thanks

**Comment by blankjul** [comment]
The `set_cv` method has been removed (the individual calculates now `cv` directly). Can you give a little bit more context when this error occurs?

**Comment by blankjul** [comment]
Has this resolved the issue?

**Comment by Junaid199f** [comment]
Sorry for late reply. I solve the issue by downgrading the Pymoo to 0.5 version.
