### ISSUE TITLE
Issue about the mutation operators

### ISSUE THREAD

**Issue by razla** [anyoptimization/pymoo#303]
Hello,

A couple of questions about the mutation operators:

Can I customize my own mutation?
If not, how can I increase the mutation rate in PM?
I work on a images and since its highly dimensional data, I need to increase the mutation rate + its amplitude - how can I do it?
I can only see prob and eta - and I'm not sure what eta is.

Thanks.

**Comment by blankjul** [comment]
Hi Razla. I know it has been a while, but have you figured out the information you need by now?

PM is based on SBX. The mutation rate is based on `prob` and `prob_var`. The amplitude is `eta` (the lower the large the range). For more information, I highly recommend reading the original SBX paper from Kalyanmoy Deb:

Kalyanmoy Deb, Karthik Sindhya, and Tatsuya Okabe. Self-adaptive simulated binary crossover for real-parameter optimization. In Proceedings of the 9th Annual Conference on Genetic and Evolutionary Computation, GECCO ‘07, 1187–1194. New York, NY, USA, 2007. ACM. URL: http://doi.acm.org/10.1145/1276958.1277190, [doi:10.1145/1276958.1277190](https://doi.org/10.1145/1276958.1277190).
