### ISSUE TITLE
Issue with PSO and small population size

### ISSUE THREAD

**Issue by mihofer** [anyoptimization/pymoo#304]
Hi,

Through a typo, I stumbled onto an issue where running PSO with a population size of 2 runs into a `ValueError: unsupported format character '-' (0x2d) at index 2`.

MWE:
```python
from pymoo.core.problem import ElementwiseProblem
from pymoo.optimize import minimize
from pymoo.algorithms.soo.nonconvex.pso import PSO

class MyProblem(ElementwiseProblem):

    def __init__(self, **kwargs):
        super().__init__(n_var=10, n_obj=1, n_ieq_constr=0, xl=-5, xu=5, **kwargs)

    def _evaluate(self, x, out, *args, **kwargs):
         out["F"] = (x ** 2).sum()

problem = MyProblem()

res = minimize(problem, PSO(pop_size=2), termination=("n_gen", 10), seed=1, save_history=False, verbose=True,)
```
The problem seems to originate from the `_adapt` method when calculating the new inertia weight yields an overflow error, which then creates an issue with the display output. Running with either `adaptive=False` , `verbose=False`, or a population size >= 3 fixes the issue. It also only appears with PSO, other algorithms like GA, ES, etc. work fine with such a small population size.

Arguably, running with such small population sizes is more of a user mistake than anything but maybe a warning could be issued if an algorithm is initialized with nonsensical values.

Otherwise, great package, works like a charm, and the documentation is really nice ( and improved with the latest release).

**Comment by marisn** [comment]
Thank yo @mihofer for a workaround. Pop > 2 really allows to move on. I wouldn't describe pop == 2 as a mistake – a good size for testing code.

Here is an actual traceback:
```
File "pymoo/optimize.py", line 67, in minimize
    res = algorithm.run()
  File "pymoo/core/algorithm.py", line 141, in run
    self.next()
  File "pymoo/core/algorithm.py", line 162, in next
    self.advance(infills=infills)
  File "pymoo/core/algorithm.py", line 232, in advance
    self._post_advance()
  File "pymoo/core/algorithm.py", line 312, in _post_advance
    self.display(self)
  File "pymoo/core/callback.py", line 27, in __call__
    self.update(algorithm)
  File "pymoo/util/display/display.py", line 23, in update
    text += output.text()
  File "pymoo/util/display/output.py", line 53, in text
    return regex.format(*[col.text() for col in self.columns])
  File "pymoo/util/display/output.py", line 53, in <listcomp>
    return regex.format(*[col.text() for col in self.columns])
  File "pymoo/util/display/column.py", line 26, in text
    return format_text(value, self.width, self.truncate)
  File "pymoo/util/display/column.py", line 43, in format_text
    text = number_to_text(value, width)
  File "pymoo/util/display/column.py", line 34, in number_to_text
    return f"%.{width - 7}E" % number
ValueError: unsupported format character '-' (0x2d) at index 2
```

**Comment by blankjul** [comment]
Thank you for pointing this out! It was just a printing issue in PSO.
