### ISSUE TITLE
CMA-ES Parameters related problem.

### ISSUE THREAD

**Issue by hfahad** [anyoptimization/pymoo#308]
Hello,
I am working at CMA-ES and I have a few questions:

1) Is it possible to use only Int values of input parameters ? I don't need a float evaluation of my function. I believe this thing will also help me to speed up my optimization.

2) what is the purpose of the initial guess within CMA-ES? because when I used a specific value of initial guess it starts from the starting not from the initial guess.

best,
Hafiz

**Comment by blankjul** [comment]
Sorry I have never come to reply to this ticket. Please open a new one if this issue still persists. 

If you like to use all the capabilities of CMAES, I recommend using the `cma` library directly (pymoo basically just wraps the function calls to it).
