### ISSUE TITLE
SBX crossover

### ISSUE THREAD

**Issue by KCrux** [anyoptimization/pymoo#309]
Hello,

if I compare your CBX algorithm with the one given in [1] (equation (5), (6) and (7) and the following paragraph), and if I didn't make some mistakes in matching the variables, ~~I think that in line 55 and 59 of [2] you should write:~~

~~`beta = 2.0 + ...` instead of~~
~~`beta = 1.0 + ...`~~

~~Otherwise at least line 47 differs from equation (5) with u <= 0.5/(1-gamma) in [1].~~

**See my comment below.**

[1] https://ieeexplore.ieee.org/document/8477746
[2] https://github.com/anyoptimization/pymoo/blob/main/pymoo/operators/crossover/sbx.py

**Comment by KCrux** [comment]
I think i did some mistakes here, sorry...

**Comment by KCrux** [comment]
Sorry for confusing everyone here, even myself. Well, the main statement remains the same: I think some values are twisted up, at least to paper [1].

I think the '2.0' in line 55: 

`beta = 1.0 + (2.0 * (y1 - _xl) / delta)`

should be not there and instead in alpha in line 42:

'alpha = 2.0 - 2.0 * np.power(beta, -(eta + 1.0))'

**Comment by blankjul** [comment]
Sorry for the late reply. Thanks for figuring it out! 
(only through such deep dives we fully understand such operators :) )
