### ISSUE TITLE
Equality constraints do not work

### ISSUE THREAD

**Issue by zwang1995** [anyoptimization/pymoo#318]
Hello, I was attempting to add an equality constraint to make sure two variables (x0 and x2) have the same value. But from the results, it seems the equality constraint does not work. 

```
from pymoo.core.problem import Problem
from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.optimize import minimize

class OptimProblem(Problem):
    def __init__(self):
        super().__init__(n_var=3, n_obj=2, n_eq_constr=1, xl=-2, xu=2)

    def _evaluate(self, x, out, *args, **kwargs):
        f_list, g_list = [], []
        F1 = (x[:,0]-1) ** 2 + x[:,1] ** 2 + x[:,2] ** 2
        F2 = x[:,0] ** 2 + (x[:,1]-1) ** 2 + x[:,2] ** 2

        out["F"] = np.column_stack([F1, F2])
        out["H"] = np.array(x[:,0] - x[:,2]).reshape(-1, 1)

algorithm = NSGA2()
problem = OptimProblem()

res = minimize(problem, algorithm, seed=42, save_history=True, verbose=True)

print("-> Best solution found: %s" % res.X)
print("-> Function value: %s" % res.F)
```

Part of the solutions are provided below, and we can find x0 and x2 do not have the same value.
```
-> Best solution found: [[ 9.99392935e-01 -2.40933039e-04  1.64089449e-03]
 [ 1.00331634e-03  1.00001028e+00  3.09432886e-03]
 [ 6.29561951e-01  3.58239706e-01 -4.29194570e-03]
 [ 8.96458414e-01  1.86068670e-01  2.03431762e-03]
...
```
I am very grateful if someone can give some hints. Thank you!

**Comment by elcf** [comment]
Equality constraints are challenging, the docs state that ["most algorithms in pymoo will not handle equality constraints efficiently".](https://pymoo.org/constraints/index.html)

You can convert equality constraints into inequality by specifying: x1-x2<=epsilon, where epsilon is a small value. You will have to play around with the epsilon to get the results you seek, but in general the smaller the epsilon, the harder the time the algorithm will have to find valid solutions.

**Comment by zwang1995** [comment]
@elcf Thank you for the hints.

**Comment by ethantenison** [comment]
@elcf how do you specify the epsilon? Is there a specific call for it? Its use for equality constraints is mentioned in another issue, but there's no example for it.
