### ISSUE TITLE
pyMOO GPU acceleration?

### ISSUE THREAD

**Issue by jacktang** [anyoptimization/pymoo#319]
Hello,

I've read pyMOO documentation, and known that pyMOO can be accelerated multi-thread/process and distributed jobs. And my question is that is it impossible to accelerate pyMOO using GPU? or the question equals to accelerating numpy using GPU? Thanks!

**Comment by blankjul** [comment]
Pymoo itself does not use/support GPU. However, you can use a GPU to evaluate multiple individuals in parallel. This can become handy if you either have a very large population size or or a lot of variables.

**Comment by jacktang** [comment]
@blankjul it is great if pymoo provides some cuda based demo. I am now working on it, if it is completed, i would like to send the PR

**Comment by cjx2020** [comment]
@jacktang Hello, now I want to use GPU to accelerate my code, but I cannot find some useful information about using cuda in pymoo. From your reply content, I know you are meeting the similar issue. Could you give me some suggestion about our common problem. Thanks a lot in advance.

**Comment by blankjul** [comment]
@jacktang Great! I am looking forward to your PR. I would also be more than happy to add it to the documentation so that users can find it directly.

I am closing this issue for now.

**Comment by jacktang** [comment]
@cjx2020 I profiled the code performance in my case and found that the problem `_evaluate` process took a lot of time in each iteration. So i mainly focused on evaluating the problem using GPU. If you try to accelerate the optimization algorithm by GPU, you may refer to AGEMOEA/2

**Comment by cjx2020** [comment]
@jacktang ok, thanks. I have used the decorator @cuda.jit to accelarate the _evaluated function, and I used the NSGA3 algorithm. I think the acceleration theory is similar.
