### ISSUE TITLE
`sample_on_unit_simplex` uses global random number generator

### ISSUE THREAD

**Issue by MLopez-Ibanez** [anyoptimization/pymoo#321]
The use of `np.random.random` changes global state:

https://github.com/anyoptimization/pymoo/blob/4dae90a8e1c10d0f858b391903d39b0ff365fd59/pymoo/util/reference_direction.py#L178

It would be better if this function was written like:
```python
def sample_on_unit_simplex(n_points, n_dim, unit_simplex_mapping="kraemer", seed = None):
  if seed is None:
     rng = np.random
  else:
    rng = np.random.default_rng(seed)
   if unit_simplex_mapping == "sum":
        rnd = map_onto_unit_simplex(rng.random((n_points, n_dim)), "sum")
...
```

and in general all functions that call `np.random` should allow providing a seed.

**Comment by blankjul** [comment]
Hi Manuel,
Great seeing you here! Because this is an internal function used by the factory I thought this should not be a problem. Are you using that function directly in your code? Any reason why `np.random.seed(n)` before calling this function wouldn't do the job?

**Comment by MLopez-Ibanez** [comment]
Hi Julian ,

Most algorithms in pymoo take a seed. One would expect that given the same
seed, the behaviour would be reproducible. However, if the algorithm calls
this function, it won't be. Yes, we can use the global rng but that means
the behaviour of the algorithm may be affected by something that happens
outside of it.

As a minor comment, using the global rng is considered legacy behaviour in
numpy that may go away some day:
https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html?highlight=random%20seed#numpy.random.seed

**Comment by MLopez-Ibanez** [comment]
And actually, it would be better if every external function that uses RNG,
uses something like:

def get_rng(seed = None):
  if seed is None or type(seed) == int:
     rng = np.random.default_rng(seed)
  return rng

 So that if seed is None or an int, it creates a new RNG, otherwise seed is
assumed to be a RNG that follows the numpy API. This way, an algorithm can
pass around an RNG instance to helper functions and the user may pass an
RNG instance or a numerical seed to the algorithm.

Internal functions may be simplified and only accept an RNG given by the
caller, and neither None nor an integer.

But the above may generate different behaviour for code currently using the
global rng because default_rng is not the same RNG (it is supposedly
better). This is why my original proposed fix still used the global one
with seed==None, to keep backwards compatibility.

**Comment by blankjul** [comment]
Thanks for all the details. I was not aware of the legacy behavior. I agree, that ideally, an algorithm has a random generator. 

At this point, this might require quite a bit of implementation effort to include this in pymoo. I am thinking of all the operators and other methods that rely on a random generator. Currently, having the seed just initialized once in the beginning globally has the upside of not having to pass the generator anytime. 

If one of your Ph.D. students or you are already working on it please let me know. I am more than happy to look at a PR.
