### ISSUE TITLE
res.X doesnt give out numerical values, instead True False 

### ISSUE THREAD

**Issue by Timbimjim** [anyoptimization/pymoo#322]
Hey, I used pymoo couple of month ago and it worked well.

I updated to the newest 0.6 version and when I run the same code I ran couple of month ago, with the older version I get solutions for F but when I try to see my feature space X it only gives out True, False arrays.

I call res.X and get:

X = [[False False  True False  True  True  True  True  True False  True  True
   True False  True False False False False False  True  True  True  True
  False  True False False  True False  True False False  True False False
  False  True  True False False False False  True  True False  True False
   True  True False  True  True False False  True False False False False
  False  True  True  True False False  True  True  True False False]
 [False False  True False  True  True  True  True  True False  True...

Instead of an array with the values for my input features. Any idea what the problem could be? This is only happening since I upgraded to 0.6 (running NSGA2).

Ty for any info

**Comment by blankjul** [comment]
Are you running binary optimization? If yes this is expected. You can use `astype` from NumPu to cast the array.

Otherwise, do you have a quick example to reproduce the error?
