### ISSUE TITLE
time termination criterion is limited to 24 hours maximum

### ISSUE THREAD

**Issue by aamorel** [anyoptimization/pymoo#323]
First thank you for the amazing framework !

Just a small detail that can be corrected really quickly in the current stable version **0.6.0**:
Time, as a termination criterion, is limited to 24 hours, which is limiting for big experiments. 

Would it be possible to change it to accept any number of hours ?

**Comment by blankjul** [comment]
Thank you! Can you elaborate on where you find that the time is limited? Are you referring to `TimeBasedTermination`?

**Comment by aamorel** [comment]
Yes exactly, this is the link to the doc:
https://pymoo.org/interface/termination.html "Based on Time"

**Comment by blankjul** [comment]
Good catch! The time formatting can only handle up to 24 hours. You can also directly provide the seconds in the current version.

For the next version, please see my commit which passes this test:

```
from pymoo.termination.max_time import TimeBasedTermination


def test_time_based_termination_more_than_one_day():
    termination = TimeBasedTermination("99:00:00")
    assert termination.max_time == 356400

    termination = TimeBasedTermination("105:10:00")
    assert termination.max_time == 378600

    termination = TimeBasedTermination("40")
    assert termination.max_time == 40

    termination = TimeBasedTermination("1:40")
    assert termination.max_time == 100

```

Does that work for you?
