### ISSUE TITLE
Pareto front is None

### ISSUE THREAD

**Issue by irecsys** [anyoptimization/pymoo#324]
Hello, I tried to adapt pymoo to my MOO problem

I can produce solutions, and use ASF or persudo weights to find "optimal" one from the solution set

I also want to plot Pareto front. However, it always returns a None object to me.

Any suggestions?

**Comment by irecsys** [comment]
what is the condition to say "converge"?

**Comment by blankjul** [comment]
What problem have you tried? Not all problems have the PF available.
