### ISSUE TITLE
Multi-objective result reading problem: "'Problem Error: F can not be set"

### ISSUE THREAD

**Issue by springonions-87** [anyoptimization/pymoo#326]
Hello!

I am new to pymoo so in general a bit lost. I'm currently running into the problem of: "('Problem Error: F can not be set, expected shape (100, 1) but provided (100, 2)', ValueError('cannot reshape array of size 200 into shape (100,1)'))" - when I am trying multi-objective algorithms. I also copied the knapsack and ZDT1 problem from this GitHub page to check if the error incurred due to mistakes in my code, but also ran into the same error. 

Any lead is appreciated thank you!

**Comment by blankjul** [comment]
Can you provide the code you have used? It looks to me that you are not setting two objectives but just one! 
(check `n_obj` in your problem to be set correctly)
