### ISSUE TITLE
Version 0.6.0 on conda-forge

### ISSUE THREAD

**Issue by cheginit** [anyoptimization/pymoo#327]
The latest version, 0.6.0, is still not available through conda-forge. Is there any plan to continue releasing pymoo via conda-forge?

**Comment by cheginit** [comment]
Right, I saw that already but since there hasn't been any activity to fix those issues, I was wondering if there's any plan to get it merged.

Since there have been breaking changes from 0.5.0 to 0.6.0, I used the 0.6.0 version in my recently developed package. I am planning to release it soon on conda-forge and if pymoo 0.6.0 will not be available on conda-forge, I have to think about alternatives.

**Comment by cyrilpic** [comment]
It actually also depends on cma=3.2.2 being added to conda. I created two PR (https://github.com/conda-forge/cma-feedstock/pull/10 and https://github.com/conda-forge/pymoo-feedstock/pull/9). Let's hope they get merged/improved quickly.

**Comment by cheginit** [comment]
I see. Thanks appreciate it.

I don't think `cma` developers are going to release a new version to the conda-forge channel. It hasn't been updated since two years ago (https://anaconda.org/conda-forge/cma). They have their own conda channel called `cma-es` that's up-to-date (https://github.com/CMA-ES/pycma).

**Comment by cyrilpic** [comment]
cma=3.2.2 in now available on conda-forge. I hope to see https://github.com/conda-forge/pymoo-feedstock/pull/9 merged soon.

**Comment by cheginit** [comment]
Great, thanks!

**Comment by cyrilpic** [comment]
It needed a bit of time, but it has been merged now and pymoo=0.6.0 should be available on conda-forge in 1-2 hours.

**Comment by cheginit** [comment]
Thanks for working on this and letting me know, appreciate it!
