### ISSUE TITLE
Optimization with sparsity inducing norms.

### ISSUE THREAD

**Issue by CompRhys** [anyoptimization/pymoo#334]
Is there any way to introduce a regularizing penalty into the pymoo optimization in order to arrive at sparse solutions? I am using NSA-II.

**Comment by blankjul** [comment]
This is part of the problem definition. You can define a second objective which is simply the number of zeros in your variables space! Indeed this is an interesting application. Feel free to comment here if you have done some more research on it. I would also be happy to put it as an example on the homepage.
