### ISSUE TITLE
Optimization over quantized input spaces

### ISSUE THREAD

**Issue by CompRhys** [anyoptimization/pymoo#335]
Is there any way in pymoo to handle optimization over a quantized input space i.e. everything rounded to nearest 0.1 for example. Applying this rounding after the design can lead to adversarial issues with the surrogate model. Rounding inside the evaluate function does not allow us to overwrite the input values that are stored in the population and used in the breeding stages.

**Comment by blankjul** [comment]
There are two ways of quite easily implementing that:

1) you use a repair operator that always round to the required precision (https://pymoo.org/operators/repair.html)

2) you directly optimize the discrete input space (https://pymoo.org/customization/discrete.html)

Let me know if that works for you.
