### ISSUE TITLE
Issue for save_history

### ISSUE THREAD

**Issue by GoossLeng** [anyoptimization/pymoo#345]
Hello, when I set save_history parameter for True, the project will go wrong and print messages: "TypeError: cannot pickle '_thread.RLock' object"

**Comment by cyrilpic** [comment]
With `save_history=True`, the algorithm is deepcopied at each generation for storage. You appear to have a RLock object and it cannot be pickled (or deepcopied).

Are you using some sort of parallelization?

**Comment by GoossLeng** [comment]
> 

Thanks for replying, some self-defined objects in problem definition cannot be deep copy. After replacing them with global variable, the code can be executed successfully.

**Comment by blankjul** [comment]
Great!
