### ISSUE TITLE
Multi-thread runner is slower than single thread in 0.6.0 version

### ISSUE THREAD

**Issue by jacktang** [anyoptimization/pymoo#347]
Hello,

I take the example for document.
```
class MyProblem(ElementwiseProblem):

    def __init__(self, **kwargs):
        super().__init__(n_var=2,
                         n_obj=2,
                         n_ieq_constr=2,
                         xl=np.array([-2, -2]),
                         xu=np.array([2, 2]),
                         **kwargs)

    def _evaluate(self, x, out, *args, **kwargs):
        f1 = 100 * (x[0] ** 2 + x[1] ** 2)
        f2 = (x[0] - 1) ** 2 + x[1] ** 2

        g1 = 2 * (x[0] - 0.1) * (x[0] - 0.9) / 0.18
        g2 = - 20 * (x[0] - 0.4) * (x[0] - 0.6) / 4.8

        out["F"] = [f1, f2]
        out["G"] = [g1, g2]
```

And set the termination as 
```
res = minimize(problem,
               algorithm,
               ("n_gen", 10000),
               verbose=True,
               seed=1)
```

1-thread takes 50 seconds and 20-threads takes 60 seconds. My server is 24 core idle. Is this one bug?

**Comment by cyrilpic** [comment]
This is most probably not a bug. Multi-threading in python is most of the time similar or slower than single thread (due to python's memory management). If you need speed ups, you should use multi-processing. However, there is an associated overhead. So, if your problem only takes 50s to run on a single core, you may not have such a large boost.

**Comment by jacktang** [comment]
@cyrilpic Thanks for the quick response!
My real problem optimization take around 1 hour to get the result using 20-thread, and yes, it is much slower than single thread. I am not familiar python so much, so I suspected the slowness caused by some race condition. That's why I take the simple example in document. 

I will try multi-processing next day. Thanks again!

**Comment by jacktang** [comment]
@cyrilpic Thanks for your suggestion! 20-processing takes 10 min to get the results. Cheers 🍻
