### ISSUE TITLE
Why hypervolume goes down

### ISSUE THREAD

**Issue by irecsys** [anyoptimization/pymoo#349]
![HV_runs=200_pop=100](https://user-images.githubusercontent.com/7389671/202092680-5e8be03d-a053-4f17-aa98-faa02c3c2b4c.png)

I guess that it could drop due to the changes in diversity

**Comment by cyrilpic** [comment]
Hi @irecsys,
This is not a bug of pymoo. Many algorithms do not guarantee strict convergence and may choose individuals whose hypervolume contribution is lower than others. You can look at the work on HypE (https://doi.org/10.1162/EVCO_a_00009) for strict hypervolume convergence.
If you are interested, please open a thread under: https://github.com/anyoptimization/pymoo/discussions

**Comment by MLopez-Ibanez** [comment]
Not only that, most algorithms cannot guarantee that the next population is not dominated by a previous one. See: https://lopez-ibanez.eu/publications#LopKnoLau2011emo (the title mentions "archiving", but the conclusions apply to any bounded-size or fixed-size multi-objective solution-set)

**Comment by MLopez-Ibanez** [comment]
The solution is to use an unbounded external archive or a hypervolume-based one.
