### ISSUE TITLE
HyperVolume does not work in version 0.5.0

### ISSUE THREAD

**Issue by hamedgibago** [anyoptimization/pymoo#350]
I installed latest version 0.5.0 and wanted to test sample code from page:
https://pymoo.org/misc/indicators.html
code:

```
from pymoo.indicators.hv import HV

ref_point = np.array([1.2, 1.2])

ind = HV(ref_point=ref_point)
print("HV", ind(A))
```

But it said:
builtins.TypeError: 'module' object is not callable

So I used instead:

```
from pymoo.vendor import hv as HH
ref_point = np.array([1.2, 1.2])
ind=HH.HyperVolume(ref_point)
t= ind.compute(A)
print(t)
```

**Comment by blankjul** [comment]
Are you referring to version 0.6.0? (this would be the latest version)

Is the issue resolved?

**Comment by hamedgibago** [comment]
> 

No it did not. I am referring to 0.5.0 version.

**Comment by blankjul** [comment]
Can you try the latest version and see if the error persists? 

I asked the clarification question because the "latest" version would be 0.6.0 at the time you asked your question, or you referred actually to 0.5.0.

**Comment by hamedgibago** [comment]
Sure, I will recompile latest version 0.6.0 for python and test if it will work. I inform you as soon as possible.

**Comment by hamedgibago** [comment]
For building new version CMakeLists.txt does not exists in source folder. Older versions building by cmake. Is it ommited in 0.6.0 and it should be built by make?

**Comment by hamedgibago** [comment]
I installed version 0.6.0 in my virtual Ubuntu linux and it worked without any bugs in this version:
![image](https://user-images.githubusercontent.com/3177023/209367732-92a7e9b4-abb8-4ec1-8bca-1e847c66c1b5.png)

**Comment by blankjul** [comment]
Great! So I can close this issue?

**Comment by hamedgibago** [comment]
Sure, thank you.
