### ISSUE TITLE
Bounds and Has_Bounds in Problem class with mixed variables

### ISSUE THREAD

**Issue by memo26167** [anyoptimization/pymoo#352]
Hello.
The `bounds` and `has_bounds` methods in the `Problem` class, when defining mixed variables, returns None values and False respectively.

Minimal example:
```from pymoo.core.problem import Problem
from pymoo.core.variable import Real, Integer, Choice, Binary
class MyProblem(Problem):
    def __init__(self, **kwargs):
        variables = {'x': Integer(bounds=(0, 10)),
                     'y': Real(bounds=(0.1, 0.99)),
                     'z': Binary()
                     }
        super().__init__(vars=variables,
                         n_obj=3,
                         **kwargs)
problem = MyProblem()
print(problem.bounds())
print(problem.has_bounds())
```
This returns:
```
(None, None)
False
```

the problematic lines of code are [these](https://github.com/anyoptimization/pymoo/blob/db63995689e446c343ca0ccb05cac8c682fcb98d/pymoo/core/problem.py#L334-L341)

Thanks

**Comment by blankjul** [comment]
Thanks for reporting that you expected a different behavior. I am not sure yet what the solution should be. 

For instance, `Binary` does not really have a lower bound, and the same holds for `Choice` (not shown in your example). 
I feel like this might either be the expected behavior or defining a new problem `MixedVariableProblem` might be a solution.

What do you think?

**Comment by blankjul** [comment]
Can you check my latest commit? It passes this test:

```
from pymoo.core.problem import Problem
from pymoo.core.variable import Real, Integer, Binary


def test_mixed_vars_bounds():
    class MyProblem(Problem):
        def __init__(self, **kwargs):
            variables = {'x': Integer(bounds=(1, 10)),
                         'y': Real(bounds=(0.1, 0.99)),
                         'z': Binary(bounds=(0, 1))
                         }
            super().__init__(vars=variables,
                             n_obj=3,
                             **kwargs)

    problem = MyProblem()

    assert problem.has_bounds()
    assert problem.xl == dict(x=1, y=0.1, z=0)
    assert problem.xu == dict(x=10, y=0.99, z=1)

```

Because the variables are a dictionary, I would as a user also expect the bounds to be a dict. What do you think?
