### ISSUE TITLE
Does NSGSII include adaptive mutation?

### ISSUE THREAD

**Issue by khoopes** [anyoptimization/pymoo#354]
Does the mutation rate of NSGAII in pymoo include adaptive mutation? I am seeing that the algorithm effectivly stops exploring the design space and all evaluations are the same after a certain number of generations. Here is my absurdly overly complex example:

```
import numpy as np
from pymoo.core.problem import ElementwiseProblem
from pymoo.algorithms.moo.nsga2 import NSGA2
import matplotlib.pyplot as plt
from pymoo.termination import get_termination
from pymoo.optimize import minimize
from pymoo.operators.mutation.pm import PM
from pymoo.operators.crossover.sbx import SBX
from pymoo.core.callback import Callback

class MyCallback(Callback):
    def __init__(self) -> None:
        super().__init__()
    def notify(self, algorithm):
        print(algorithm.n_gen, min([p.X[0] for p in algorithm.pop]), max([p.X[0] for p in algorithm.pop]))

def metric(x):
    return (-1*x) * np.sin(x**2.0) + (x-10.0) * np.sin((x-10.0)**2.0)

class MyProblem(ElementwiseProblem):
    def __init__(self):
        super().__init__(n_var=1,
                         n_obj=1,
                         n_ieq_constr=0,
                         xl=np.array([0]),
                         xu=np.array([14]))

    def _evaluate(self, X, out, *args, **kwargs):
        x = X[0]
        f1 = metric(x)
        out["F"] = [f1]

algorithm = NSGA2(
    pop_size=200,
    n_offsprings=30,
    crossover=SBX(eta=20),
    mutation=PM(prob=0.5, eta=20.0),
    callback=MyCallback(),
    eliminate_duplicates=True
)

problem = MyProblem()
termination = get_termination("n_gen", 200)
res = minimize(problem,
               algorithm,
               termination,
               seed=3,
               save_history=True,
               verbose=False)


x = np.linspace(0,14,10000)
plt.plot(x,(-1*x) * np.sin(x**2.0) + (x-10.0) * np.sin((x-10.0)**2.0),label='Metric Function')
X = np.array([[float(p.X) for p in h.pop] for h in res.history]).flatten()
F = np.array([[float(p.F) for p in h.pop] for h in res.history]).flatten()
plt.plot(X,F,'xk',alpha=0.3,label='All Evaluations')
plt.plot(res.X,res.F,'ro',label='Optimum')
plt.legend()
plt.grid()
plt.tight_layout()
plt.savefig('res.mutation.png',dpi=150)

plt.close('all')
X = [[float(p.X) for p in h.pop] for h in res.history]
for n,x in enumerate(X):
    plt.plot(np.ones_like(x)*n, x,'kx')
plt.grid()
plt.xlabel('Generation')
plt.ylabel('X')
plt.tight_layout()
plt.savefig('res.mutation.branch.png', dpi=150)
```

The algorithm finds the global minimum, but by about generation 50, it's no longer exploring at all as you can see in the `res.mutation.branch.png` figure which plots all evaluations by generation. It's the same story even if I change the `eta` parameter on mutation to make the mutation more aggressive. I thought that it would always mutate regardless of how many generations it had done to keep exploring, but it does not seem to do that.

What am I missing?

Thanks,

**Comment by khoopes** [comment]
Ah OK. That makes sense. I think for some reason I had it in my mind that the population stored would be all evaluations, I reworked my example to store all new evaluations per generation and I can see that it is still exploring the design space as I anticipated. As you said, those designs are just not making it to the population because they are not as fit.

I did that by just having my function evaluation store all the evaluations in a separate variable, are all the evaluations also stored by pymoo or does it only save the population history?

**Comment by blankjul** [comment]
There are not stored by default, because depending on the length of the run and population size this can easily cause memory issues. 

Either use `save_history` to store the whole algorithm object or use a `Callback` (https://pymoo.org/interface/callback.html) to have more control over what is stored.
