### ISSUE TITLE
PSO constraint optimization

### ISSUE THREAD

**Issue by 12lwx** [anyoptimization/pymoo#356]
Recently, I'm using pso to solve the single objective function. This optimization is an integer programming with constraints, but it doesn't seem to have any effect in the running process. This is my code.At present, there are about 89 unequal constraints and 73 equal constraints.
problem = MyProblem(data.m_time[i],data.num_person[i],data.a_num[i],data.b_num[i],data.c_num[i],
                                data.d_num[i],data.e_num[i],data.person_dict[i],data.ability[i])
    
    algorithm = PSO(pop_size=96,sampling=IntegerRandomSampling())
    res = minimize(problem,
                   algorithm,
                   ('n_gen',2000),
                   seed=1,
                   verbose=False)
    print("Best solution found: \nX = %s\nF = %s" % (res.X, res.F))

**Comment by blankjul** [comment]
The PSO algorithm is designed to work in a continuous space. Also, the basic version of the algorithm does not support constraints. 

I recommend using a GA in your case: https://pymoo.org/customization/discrete.html
