### ISSUE TITLE
files licensed under GPL 

### ISSUE THREAD

**Issue by jamesxuxu** [anyoptimization/pymoo#361]
Dear Julian,

I noticed several files licensed under GPL, e.g.
https://github.com/anyoptimization/pymoo/blob/main/pymoo/vendor/hv.py
https://github.com/anyoptimization/pymoo/blob/main/pymoo/cython/vendor/defs.h

Under my understanding, these GPL files are not compatible with the Apache license of pymoo project. If these GPL files are included, the pymoo project's license has to be GPL instead of Apache. Please check [https://www.apache.org/licenses/GPL-compatibility.html](url)

 Is there any way to get rid of these files?

**Comment by blankjul** [comment]
Thank you for bringing this up. I was not aware that there is a license issue.
Let me contact the authors of the packages and figure something out. Otherwise, I will have to remove them in the next version.

**Comment by blankjul** [comment]
**vendor/hv.py:** I have been in touch with Simon Wessing regarding the license problem. pymoo has now official permission to include his implementation.

**vendor/defs.h** The package the source code was from does not exist anymore and has been taken offline. Only two methods of the header files were necessary anyway, so the dependency could be resolved entirely.

Thank you for raising this issue!
