### ISSUE TITLE
Giving a custom initial population

### ISSUE THREAD

**Issue by haritha-paul** [anyoptimization/pymoo#366]
Hi, I've been using pymoo in my multi-objective optimization problem. I have the initial population for the multi-objective algorithm 
(say, NSGA-2) generated by another algorithm.

How can I feed a custom input population in pymoo? Is there a provision for that? I want to give the population list generated into NSGA2 algorithm for genetic operations.

Note: My input population are floating point numbers.

**Comment by bruscalia** [comment]
Hi, @haritha-paul ! You can pass your previous population (or numpy array) as the sampling argument in either the new algorithm initialization or as a keyword argument to the minimize interface, which will override the sampling operator of the algorithm.

Let me know if it works for you!

**Comment by haritha-paul** [comment]
Thank you so much for your reply. I'll try and let you know if it works!

**Comment by blankjul** [comment]
@haritha-paul You can also directly follow this tutorial available in the documentation: 
https://pymoo.org/customization/initialization.html

Feel free to reopen this issue if not resolved.
