### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'warnings'

### ISSUE THREAD

**Issue by lacava** [anyoptimization/pymoo#369]
encountered when running [high_tradeoff](https://github.com/anyoptimization/pymoo/blob/main/pymoo/mcdm/high_tradeoff.py) . 

it would be better for `np.warnings.filterwarnings('ignore')` to directly use `warnings` (reference): https://stackoverflow.com/questions/29347987/why-cant-i-suppress-numpy-warnings

> numpy.warnings is just an accidental alias to the stdlib warnings module. numpy/__init__.py imports it to use it but neglects to delete it from its namespace. Don't use numpy.warnings; just import warnings 

that is, change

https://github.com/anyoptimization/pymoo/blob/50e4a1f5386814e90ce56cf03e07468ce30ecbb5/pymoo/mcdm/high_tradeoff.py#L32

to `warnings.filterwarnings('ignore')`

more info:

```
numpy                     1.24.1           py39h223a676_0    conda-forge
pymoo                     0.6.0.1          py39h2ad29b5_1    conda-forge
python                    3.9.15          hba424b6_0_cpython    conda-forge
```

error: 
```
  File "/home/bill/miniconda3/envs/exp-fomo/lib/python3.9/site-packages/pymoo/core/indicator.py", line 15, in __call__
    return self.do(F, *args, **kwargs)
  File "/home/bill/miniconda3/envs/exp-fomo/lib/python3.9/site-packages/pymoo/core/indicator.py", line 30, in do
    return self._do(F, *args, **kwargs)
  File "/home/bill/miniconda3/envs/exp-fomo/lib/python3.9/site-packages/pymoo/mcdm/high_tradeoff.py", line 32, in _do
    np.warnings.filterwarnings('ignore')
  File "/home/bill/miniconda3/envs/exp-fomo/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'warnings'
```

**Comment by blankjul** [comment]
Thanks for creating this issue! The last commit should fix this. Please reopen the issue if not.
