### ISSUE TITLE
Questions about recording the time for each generation of GA

### ISSUE THREAD

**Issue by rongqipan** [anyoptimization/pymoo#370]
Hi,

Thanks for the good work!

I have a question for recording the time for each generation.

I used something like:

res = minimize(problem,
               algorithm,
               ('n_gen', 60),
               seed=1,
               verbose=True,
              save_history=True)

Then I used res.history[0].start_time. However the start time for each generation are the same, I guess it is the setup time not the actual strart running time.

Is there any way to record the running (execution) time for each generation (iteration) of genetic algorithm?

Thanks.
Rongqi

**Comment by blankjul** [comment]
Checkout the `Callback` feature: https://pymoo.org/interface/callback.html

This should be exactly what you are searching for.
