### ISSUE TITLE
NSGA II Pareto is limited to 300 - Newbie Question

### ISSUE THREAD

**Issue by hus2525** [anyoptimization/pymoo#371]
Hi,

Apologies if this is obvious, but the pareto front seems to cut off at 300. I have tried optimising different problems but the same keeps happening. I'm wondering if there is a parameter that I'm missing?

See output below:
<img width="432" alt="Screenshot 2023-01-23 at 21 00 08" src="https://user-images.githubusercontent.com/123417754/214153002-30d02f52-df6b-4c73-8c8c-5d98c9bb652e.png">

Here is part of the code I'm running, thank you in advance:

        fevals = len(lb) * 5000
        popsize = 100 * len(lb)
        test_problem = MyProblem(len(ub), ub, lb, model)
        algorithm = NSGA2(
            pop_size=popsize,
            sampling=get_sampling("real_random"),
            crossover=get_crossover("real_sbx", prob=0.8, eta=20),
            mutation=get_mutation("real_pm", prob=1/len(lb), eta=20),
            eliminate_duplicates=True,
            #n_offspring=10
        )
        termination = get_termination("n_gen", 50)
        res = minimize(
            test_problem,
            algorithm,
            termination,
            seed=1,
            save_history=False,
            verbose=True,
        )
        xfront = res.X
        pfront = res.F

**Comment by blankjul** [comment]
The maximum amount of non-dominated solutions is `pop_size`.  I can't see the value in your code, but I am pretty sure you are setting it to 300. You can increase the value to get more points.

As an alternative, you can use a Callback  (https://pymoo.org/interface/callback.html) to store more solutions than that in a custom data structure.
