### ISSUE TITLE
How to continue the calculation based on the results of the previous generation?

### ISSUE THREAD

**Issue by cjx2020** [anyoptimization/pymoo#373]
Since I am not clear about the convergence of the my problem, I first conducted the 10th generation. When I started the next round of optimization based on the results of the 10th generation, that is the 10th genenration population was set as the initial sampling population, but I found that the results of the 11th generation were different from those of the 10th generation. And I have to wait for more time to generate the same results as 10th generation. What can I do if I want to continue to optimize based on my previous results.

**Comment by blankjul** [comment]
Checkout checkpointing: https://pymoo.org/misc/checkpoint.html

Otherwise, you can also re-initialize an algorithm with the previous population you have stored:
https://pymoo.org/customization/initialization.html

**Comment by cjx2020** [comment]
thanks, sir. If I want to use the checkpoint function more than once, what should I do? I find that the checkpoint function can be only used once. My problem is so complexed and time-consuming and I have to try many times to adjust the termination generation.

**Comment by cjx2020** [comment]
My problem has nine obejectives, and so I used the MixedVariableSampling function to generate the initial population whose data type is dict, and then I replace the sampling population by the last generation populaiton generated by my last running.

I have tested the initialization function with the above method, but I find the first generation in the second running result is different from the last generation result in the first running. And the screen is below. I can't find the real reason. 

I guess the main reason is that the initialization function is only select some populaiton from my former result, and generate other populaiton, so the result is different between the two running. 

![e6a53ec42949866577aeca344d60205](https://user-images.githubusercontent.com/63455193/215377894-2bef32ed-f2d1-4699-acee-b582d171fbd8.png)

**Comment by blankjul** [comment]
Check out the checkpoint again. You can dump the algorithm object into a file. Then, you can continue optimizing from each checkpoint as much as you want. 

Regarding the screenshot above, I would need some code example with some comments to see what you are trying to accomplish.

**Comment by cjx2020** [comment]
ok, thanks. I think the main reason may be the initial_pop function coded by me. I want to read the latest population from excel file, so I create it. But when I run this funciton with the remaining code, I get the different result I have mentioned above.

The main function is below:

# function of generate initial population based on the latest running
def initial_pop(excel_file_location=None,
                sheet_name=None,
                problem=None,
                pop_size=None):

    '''
    :param excel_file_location: the .xlsx file location saving the populaiton
    :param sheet_name: the name of sheet saving the last population
    :param problem: the optimal problem object
    :param pop_size: size of population
    :return: sampling population
    '''
    import pandas as pd
    from pymoo.core.mixed import MixedVariableSampling

    file_location = excel_file_location
    df = pd.read_excel(file_location, sheet_name)
    ori_sample = df.iloc[:, 1::].values

    var_name = [] # the name of dict index
    var_n = problem.n_var
    for k in range(var_n):
        var_name.append(f"x{k:04}")

    sampling = MixedVariableSampling().do(problem, pop_size)

    for j in range(pop_size):
        sampling[j].X = dict(zip(var_name, ori_sample[j]))  # replace with populaiton of last generation 

    return sampling

# initialization
initial_sampling = initial_pop(excel_file_location=excel_file_location,
                               sheet_name=sheet_name,
                               problem=my_problem,
                               pop_size=pop_size)

ref_dirs = get_reference_directions("energy", n_dim=n_dim, n_points=n_points, seed=2)

# setting of algorithm
algorithm = NSGA3(pop_size=pop_size,
                  ref_dirs=ref_dirs,
                  sampling=initial_sampling,
                  mating=MixedVariableMating(eliminate_duplicates=MixedVariableDuplicateElimination()),
                  eliminate_duplicates=MixedVariableDuplicateElimination())

**Comment by cjx2020** [comment]
the below code is part of my problem definition, my problem has different boundary and type. so I create the problem class with the method you mentioned in https://pymoo.org/customization/mixed.html. The name of this part is Multi-objective Optimization With Mixed Variables.



        variables = dict()
        for i in range(self.total_hour):

            for j in range(0, tcv_num): 
                k = self.decision_num * i + j
                variables[f"x{k:04}"] = Integer(bounds=(1, 50000))

            for u in range(0, fcv_num):
                m = self.decision_num * i + tcv_num + u     #11  # tcv_num + fcv_num - 1
                variables[f"x{m:04}"] = Real(bounds=(0, 0.2)) 

            for f in range(0, prv_num):
                n = self.decision_num * i + tcv_num + fcv_num + f      # 12  tcv_num + fcv_num + prv_num - 1
                variables[f"x{n:04}"] = Real(bounds=(0, 50)) 

            for e in range(0, psv_num):
                p = self.decision_num * i + tcv_num + fcv_num + prv_num + e   # 13  tcv_num + fcv_num + prv_num + pbv_num - 1
                variables[f"x{p:04}"] = Real(bounds=(0, 60))

            for t in range(0, pbv_num):
                w = self.decision_num * i + tcv_num + fcv_num + prv_num + psv_num + t
                variables[f"x{w:04}"] = Integer(bounds=(0, 1))  

            for r in range(pump_num):
                s = self.decision_num * i + tcv_num + fcv_num + prv_num + psv_num + pbv_num + r
                variables[f"x{s:04}"] = Integer(bounds=(0, 1))  

        super().__init__(
            vars=variables,
            n_obj=np.sum(whether_cal),
            n_ieq_constr=n_ieq_constr, 
            n_eq_constr=0,
            )

**Comment by cjx2020** [comment]
@blankjul  When I use checkpoint and the multiprocessing, simultaneously.  One error exist. It exists when I load the checkpoint to calculate based on  the previous result. Could you give me some advise to solve it ?


Traceback (most recent call last):
  File "D:\program\battle2022_modify_ver\my_core\20230201\optimal_run_03.py", line 287, in <module>
    main()
  File "D:\program\battle2022_modify_ver\my_core\20230201\optimal_run_03.py", line 262, in main
    res = res_cal(problem=my_problem, checkpoint=checkpoint, output=MyOutput())
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\optimize.py", line 67, in minimize
    res = algorithm.run()
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\algorithm.py", line 141, in run
    self.next()
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\algorithm.py", line 161, in next
    self.evaluator.eval(self.problem, infills, algorithm=self)
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\evaluator.py", line 69, in eval
    self._eval(problem, pop[I], evaluate_values_of, **kwargs)
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\evaluator.py", line 90, in _eval
    out = problem.evaluate(X, return_values_of=evaluate_values_of, return_as_dictionary=True, **kwargs)
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\problem.py", line 187, in evaluate
    _out = self.do(X, return_values_of, *args, **kwargs)
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\problem.py", line 227, in do
    self._evaluate_elementwise(X, out, *args, **kwargs)
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\problem.py", line 245, in _evaluate_elementwise
    elems = self.elementwise_runner(f, X)
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\problem.py", line 37, in __call__
    return list(self.starmap(f, [[x] for x in X]))
AttributeError: 'StarmapParallelization' object has no attribute 'starmap'

Process finished with exit code 1

**Comment by blankjul** [comment]
Does it work without parallelization?

@cyrilpic Do you have any clue what it might be?

**Comment by cjx2020** [comment]
yeah,it can work without parallelization.

**Comment by cjx2020** [comment]
I guess some contradiction exist between checkpoint and multiprocessing. When I give up the element_elementwise_runner=runner in my problem defination, my code work well without any error.

**Comment by cjx2020** [comment]
@blankjul I have find some introduction from "Does it support multi processor? #30" 

So, I can't use the multiprocessing when I start from stroed checkpoint? This problem can be solved in the latest pymoo version?

> Dear Julian,
> 
> I want to ask a follow-up question about parallelization. I followed the pymoo documentation for parallelization with `multiprocessing` and successfully parallelized my evaluations. However, from my test, **when trying to continue the `minimize` process from stored checkpoint, the parallelization does not work any more.**
> 
> I used normal settings to save the checkpoint to checkpoint.npy and loaded it. Everything else remains the same as the successfully parallelized version. I wonder if the minimization from a checkpoint can be parallelized. Thanks in advance!


> At this point, the parallelization is disabled after loading from a checkpoint. The reason for that is the limitation of Python to serialize a thread or process pool.
> 
> One workaround is that you can implement your own parallelization in your problem. After loading from the checkpoint, you set `algorithm.problem` to your implementation with an initialized thread or process pool.

**Comment by cyrilpic** [comment]
@cjx2020: FYI, this is also not a bug or issue of pymoo, and it would be better discussed on [discord](https://discord.gg/DUCGrvqWEM) or in the [discussion tab](https://github.com/anyoptimization/pymoo/discussions).


You can use checkpoints and parallelization, but you need to reconfigure the parallelization after reloading the algorithm from the disk:

```python
checkpoint.problem.elementwise_runner = runner
```

**Comment by cjx2020** [comment]
ok, it works well. I have another question about the problem defination. Could the problem defined by the use of Problem (vectorized)[¶](https://pymoo.org/problems/definition.html#Problem-(vectorized))  be speed up by multiprocess ? And which one could save more time between the vectorized problem defination and the ElementwiseProblem (loop)[¶](https://pymoo.org/problems/definition.html#ElementwiseProblem-(loop)) defination?

**Comment by cyrilpic** [comment]
If you can write your problem in a vectorized form, this will be the fastest. Multiprocessing in a vectorized context wouldn't make sense most of the time. If the vector operations are very large, then you could get some speed-up by moving these operations to a GPU.

**Comment by cjx2020** [comment]
ok,thanks for you reply. My problem includes many different type variables, so I define my problem according to Multi-objective Optimization With Mixed Variables[¶](https://pymoo.org/customization/mixed.html#Multi-objective-Optimization-With-Mixed-Variables). But I can find any example to define the problem including many different type variables with the vectorized problem class. Could you give some sample example to show it ?

**Comment by cyrilpic** [comment]
Mixed-integer linear programs (MILP) are an example of mixed-variable problems that can be vectorized. This is not my area of expertise, so I don't have pymoo examples.

**Comment by cjx2020** [comment]
@blankjul do  you have some example about this question ?

> ok,thanks for you reply. My problem includes many different type variables, so I define my problem according to Multi-objective Optimization With Mixed Variables[¶](https://pymoo.org/customization/mixed.html#Multi-objective-Optimization-With-Mixed-Variables). But I can not find any example to define the problem including many different type variables with the vectorized problem class. Could you give some sample example to show it ?

**Comment by blankjul** [comment]
What @cyrilpic mentioned is correct. In Python, you can not serialize a runner pool. Thus, you will have to re-initialize it if you want to use a checkpoint (it is rather a limitation of Python than pymoo I would say).

What prevents you from doing this: https://pymoo.org/customization/mixed.html

And then in the `_evaluate` function vectorize what do you want to parallelize?

**Comment by cjx2020** [comment]
Sorry, maybe I don't make it clear. What prevent me is how to realize "Multi-objective Optimization With Mixed Variables[¶](https://pymoo.org/customization/mixed.html#Multi-objective-Optimization-With-Mixed-Variables)"(https://pymoo.org/customization/mixed.html) with the problem class rather than elementwise class.  So that I can accelerate my code.

**Comment by schmoelder** [comment]
Hijacking this issue since the original question was about continuing from a previous generation.

> Check out the checkpoint again. You can dump the algorithm object into a file. Then, you can continue optimizing from each checkpoint as much as you want.

My issue with that is that I don't want to dump files using pickle because I would like to transfer (intermediate) results across multiple machines and pickle files are not ideal for that (for security reasons). So some other way to reinitialize would be great. 

I already store the final population separately and reinitialize from that. But if I understand correctly, `algorithm.opt.X` can also contain individuals which are not necessarily in the latest population, right? So can I simply "set" that after reinitializing?

Other than that, it's mostly about setting `n_max_gen` and `n_max_evals`. Is there a way to do that? Otherwise it's not too difficult to check that manually in my main optimization loop but it would be convenient. :nerd_face:

**Comment by cjx2020** [comment]
When I load the checkpoint file to continue next calculation, the memory of checkpoint is so huge, so how can I extract the final population from the former checkpoint file to serve as the new checkpoint to continue calculation, so that I can diminish the memory usage when I run my code. That is I don't want to save all the former population when I print pymoo result,  I only chose the last population to input my minimize function as the algorithm.
<img width="943" alt="issue" src="https://user-images.githubusercontent.com/63455193/216768368-627900b3-3780-49b0-8715-348c867cb20b.png">

**Comment by blankjul** [comment]
Just store the population in each iteration. Use `algorithm.pop` which will be small and reload this if needed. This should do the job.

**Comment by blankjul** [comment]
I highly recommended using an IDE (such as Pycharm) where you can inspect objects during runtime (just debug), which can help you a lot to extract the information you need.

**Comment by cjx2020** [comment]
OK, thanks for your reply.
