### ISSUE TITLE
operators warning error: RuntimeWarning: invalid value encountered in power

### ISSUE THREAD

**Issue by cjx2020** [anyoptimization/pymoo#376]
This is my error, could you give me some advice to avoid it?

![001](https://user-images.githubusercontent.com/63455193/216325339-e7623bd6-cfdc-4f57-9fe8-90ce6802a40a.png)

**Comment by blankjul** [comment]
I am going to close this issue. For direct coding support feel free to join our discord server and ask the community. 
Please provide some context (what are you trying to do?) and some reproducible code next time. 
By just posting your error message, it is very unlikely you will get the issue resolved.
