### ISSUE TITLE
ASF Decision Making

### ISSUE THREAD

**Issue by 1234shel** [anyoptimization/pymoo#387]
I am using ASF on a custom problem to identify the solution of interest. I would ideally like to pick the solution with weights 0.5,0.5. However when I try this with ASF it keeps giving me the extreme points as opposed to the one closer to the middle of the Pareto front. I would like to know why this happening? 

```
decomp = ASF()
I = decomp(norm_F, weights).argmax()
print("Best regarding decomposition: Point %s - %s, - %s" % (I, res.F[I], res.X[I]))
```
![Screen Shot 2023-02-22 at 12 26 40 pm](https://user-images.githubusercontent.com/45558418/220505537-530c0b18-d74a-49c0-94dd-215f66f348dd.png)

**Comment by blankjul** [comment]
pymoo always assume minimization. Please check if `norm_F * [-1, -1]` returns the desired result?
