### ISSUE TITLE
Invalid integer sampling when upper and lower bounds are the same

### ISSUE THREAD

**Issue by BradleyFeest** [anyoptimization/pymoo#388]
Hi all,

The issue occurs when using IntRandomSampling (potentially with the other sampling functions as well, but I didn't test them) as the sampling function - if you set the upper and lower bounds of one of the variables to the same number, it will return numbers outside of that "range". This occurs on version 0.6.0, but did not occur on 0.4.2.2 (I recently upgraded). This is obviously a pretty niche case - why even include constant variables in the optimization? But, I figured I'd share the issue nonetheless, especially since there is a comment in the ZeroToOneNormalization class attempting to handle the case where the bounds are the same.

Code to reproduce:
```
from pymoo.core.problem import ElementwiseProblem
from pymoo.operators.sampling.rnd import IntegerRandomSampling

problem = ElementwiseProblem(
    n_var = 3,
    n_obj = 1,
    xl = [1, 1, 1],
    xu = [3, 1, 5]
)

sampler = IntegerRandomSampling()
samples = sampler.do(
    problem,
    10)

for sample in samples:
    print(sample.X)
```

When running the above, you'll see an output like:
`[1 2 5]
[2 2 4]
[1 1 2]
[3 1 4]
[2 2 4]
[2 1 4]
[2 2 1]
[2 1 3]
[2 1 5]
[2 2 2]`

As you can see, the 2nd value (where the upper and lower bounds are both 1) is often returning a value of 2.

I believe the issue is in the ZeroToOneNormalization "backward" function. This line
`X[..., xl_only] = N[..., xl_only] + xl[xl_only]`
should probably be
`X[..., xl_only] = xl[xl_only]`
in order to set the value to the lower bound directly. Or perhaps the case where the bounds are equal needs to be handled separately, instead of lumping it in with the calculations where only the lower bound is defined.

**Comment by blankjul** [comment]
Thanks for reporting this! Can you please check out my latest commit (shown above)?

That fixes at least the code snippet you have provided.

**Comment by blankjul** [comment]
Please let me know if the rounding repair during crossover and mutation work in this case.
A quick hack is defining the variable as a constant and removing it entirely. But 100% agree that the code should run even if they are equal.

**Comment by BradleyFeest** [comment]
Thanks for the quick reply and fix!

The commit you pushed (6795ac) does fix the issue for the IntegerRandomSampling. 

Out of curiosity, I used the same test code but with the FloatRandomSampling class instead and the issue actually appears there as well. Since your fix was to the IntegerRandomSampling code alone, it did not fix the same case for the FloatRandomSampling class.

The rounding repair seems to work fine (the bounds are honored, even when the same).

**Comment by blankjul** [comment]
You are right it was not working for FloatRandomSampling yet. With the new commit, even this should work.

I am not sure if that is robust for all algorithms though. Because for each of them bounds are treated a little differently.
