### ISSUE TITLE
Multiple repair operators

### ISSUE THREAD

**Issue by CompRhys** [anyoptimization/pymoo#391]
It would be great to have the ability to compose repair operations i.e. such that sometimes I only apply `r1` sometimes `r1` followed by `r2` and other times just `r2` alone without having to make a new repair class for each combination. How would be the best way to implement this from the developers perspective? I am leaning towards a `MultiRepair` class that is initialised with a list of `Repair` operators and applies them in sequence?

**Comment by blankjul** [comment]
Yes exactly! You can create a `MultiRepair` class which combines several repairs. I have actually done this myself in the past and that works pretty well!
