### ISSUE TITLE
AttributeError: 'numpy.int64' object has no attribute 'get'

### ISSUE THREAD

**Issue by LorenzoBonasera** [anyoptimization/pymoo#393]
It still does not work. This error comes from the line:

File "C:....\pymoo\core\crossover.py", line 31, in
X = np.swapaxes(np.array([[parent.get("X") for parent in mating] for mating in pop]), 0, 1)
AttributeError: 'numpy.int64' object has no attribute 'get'

**Comment by blankjul** [comment]
Closed because of duplicate. See #353 

Please provide an example for us to reproduce the error.
