### ISSUE TITLE
Vectorize Evaluation in Elementwise Problems?

### ISSUE THREAD

**Issue by Lyleregenwetter** [anyoptimization/pymoo#394]
Hi Julian, 

Thanks so much for this amazing repo. I've been using it for years and it's my go-to for MOO problems. 

I'm working on a project with mixed variables and I'd very much like to vectorize the evaluation. From the documentation, it seems that the only way to define mixed variable problems is through the elementwise problem subclass. It seems vectorized evaluation is not supported in elementwise problems, but I don't see any particular reason why it can't be (each element in the dictionary could just be a 1D array). Is there a particular reason why mixed variable problems must be evaluated on an elementwise basis?

I've tried redefining a few of the Problem class functions to achieve my goal but it got messy pretty quickly. I may come up with a solution in the next couple days, in which case I'll close this issue, but figured I'd check if you have a clean solution for this or something I may have missed in the documentation. 

Thanks!
-Lyle

**Comment by blankjul** [comment]
Thanks for your positive feedback!

You can also use the vectorized version of a problem. 

```from pymoo.core.mixed import MixedVariableGA
import numpy as np

from pymoo.core.mixed import MixedVariableGA
from pymoo.core.problem import Problem
from pymoo.core.variable import Real, Integer, Binary, Choice
from pymoo.operators.survival.rank_and_crowding import RankAndCrowding
from pymoo.optimize import minimize
from pymoo.visualization.scatter import Scatter


class MultiObjectiveMixedVariableProblem(Problem):

    def __init__(self, **kwargs):
        vars = {
            "b": Binary(),
            "x": Choice(options=["nothing", "multiply"]),
            "y": Integer(bounds=(-2, 2)),
            "z": Real(bounds=(-5, 5)),
        }
        super().__init__(vars=vars, n_obj=2, n_ieq_constr=0, **kwargs)

    def _evaluate(self, vX, out, *args, **kwargs):

        F = []

        for X in vX:
            
            b, x, z, y = X["b"], X["x"], X["z"], X["y"]

            f1 = z ** 2 + y ** 2
            f2 = (z + 2) ** 2 + (y - 1) ** 2

            if b:
                f2 = 100 * f2

            if x == "multiply":
                f2 = 10 * f2

            F.append([f1, f2])

        out["F"] = np.array(F)


problem = MultiObjectiveMixedVariableProblem()

algorithm = MixedVariableGA(pop_size=20, survival=RankAndCrowding())

res = minimize(problem,
               algorithm,
               ('n_gen', 50),
               seed=1,
               verbose=False)

plot = Scatter()
plot.add(problem.pareto_front(), plot_type="line", color="black", alpha=0.7)
plot.add(res.F, facecolor="none", edgecolor="red")
plot.show()
```

Feel free to fill the `_evaluate` in a vectorized manner (I have not done this above).
Consider that bumpy will have to deal with mixed variable types if you do so.

**Comment by Lyleregenwetter** [comment]
Beautiful! What a nice simple fix. I guess I incorrectly assumed that elementwise problems were necessary to deal with mixed types. 

In case anyone stumbles upon this, here's a nice 1-liner using pandas to convert vX back to an array:
pd.DataFrame.from_records(vX).values

By the way, someone opened another issue on this, but this line from your code errored out for me:

`from pymoo.operators.survival.rank_and_crowding import RankAndCrowding`

I am using NSGA-II with mixed variable operators anyways so that was not an issue for me, but figured I'd mention it.

**Comment by Lyleregenwetter** [comment]
Julian, while we have this thread open, if I could ask you another quick question:

I am randomly hitting this assert in pymoo.core.termination, and I wonder if it's because my evaluate function has a small amount of stochasticity, meaning that it's possible to `regress' in a step. 

`assert progress >= 0.0`

In your expert opinion, am I correctly diagnosing the cause here?  And is there an easy way to fix this without changing pymoo internal code? Thanks!

**Comment by Lyleregenwetter** [comment]
Closing issue. Thanks so much for the help!
