### ISSUE TITLE
Failed import of pymoo.operators.survival.rank_and_crowding with pymoo=0.6.0

### ISSUE THREAD

**Issue by georgiachanning** [anyoptimization/pymoo#395]
`from pymoo.operators.survival.rank_and_crowding import RankAndCrowding` results in `ModuleNotFoundError: No module named 'pymoo.operators.survival.rank_and_crowding'`. A la NSGA2. `pip install -U pymoo` results in this issue.

**Comment by Lyleregenwetter** [comment]
Experienced the same with conda.

**Comment by cyrilpic** [comment]
The module `pymoo.operators.survival.rank_and_crowding` doesn't exist in a release version of pymoo (0.6.0.1 or earlier). In these versions, the rank and crowding operator is implemented in `pymoo.algorithms.moo.nsga2`.
