### ISSUE TITLE
Pymoo is resetting the global numpy.random seed

### ISSUE THREAD

**Issue by LucasAlegre** [anyoptimization/pymoo#413]
Pymoo calls `numpy.random.seed(seed)` when a seed is given to some of the functions. For instance, `get_reference_directions`:
https://github.com/anyoptimization/pymoo/blob/4dae90a8e1c10d0f858b391903d39b0ff365fd59/pymoo/util/reference_direction.py#L43

This is a problem as it has serious effects in the code of the user. For instance, if my code does something like:

```
x = my_random_func()
get_reference_directions(seed=42)
y = my_random_func()
```

Then, x and y will be equal, because of pymoo changing the global seed. Ideally, pymoo should use a dedicated Generator, as recommended here: https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html

**Comment by blankjul** [comment]
Hey Lucas, thanks for pointing this out. 
I know for the `minimize` function this is also a problem. However, there this requires a lot of changes. 

For the reference directions, this should be an easier fix. Can you create a PR for the `reference_directions` function?

**Comment by jacktang** [comment]
If no one is going to send the PR, I would like to fix this bug.

**Comment by MLopez-Ibanez** [comment]
See also https://github.com/anyoptimization/pymoo/issues/321

**Comment by blankjul** [comment]
Just merged your PR. Thanks!
