### ISSUE TITLE
ZeroToOneNormalization.forward returns the value which out of [0, 1] 

### ISSUE THREAD

**Issue by jacktang** [anyoptimization/pymoo#414]
Hello there!

The value of ZeroToOneNormalization.forward is out of [0, 1]. Is that a bug? Here is the code to reproduce the case

```
from pymoo.util.normalization import Normalization, normalize

F= np.array([[1.5789601, 0.50812683]])
c_ideal= [1.58129326,0.51329363]
c_nadir= [1.58129326,0.51329363]
n=normalize(F, c_ideal, c_nadir) # NOTE: c_nadir and c_ideal is the same point
print(n). # n = [[-0.00233316 -0.0051668 ]]
```

Regards
/Jack

**Comment by cyrilpic** [comment]
Hi Jack,
The ZeroToOneNormalization is mostly used to map points between the ideal and the nadir points to 0, 1 (0 -> ideal, 1 -> nadir). As such, points that are worse than the nadir or better than the ideal are outside of [0, 1].
I'm actually surprised that you don't run into more problem by passing the same point as upper and lower bounds (a division by zero). If you want all the points to be in [0, 1], then you can use `normalize(F)`.

**Comment by jacktang** [comment]
Hello @cyrilpic,

Thanks for your reply! the code comes from running_metric.py(line 44)

```
        # normalize all previous generations with respect to current ideal and nadir
        N = [normalize(e["F"], c_ideal, c_nadir) for e in history]

```
I debug the source code because in my problem, the init value of f_delta (IGD indicator)is very large(1e5), and I am very confused since the objective function is normalized, and in around 10th generation, cv_min and cv_avg is 0.

![image](https://user-images.githubusercontent.com/44341/229270238-1248a09b-2c82-495b-b9d9-2459a6167262.png)

**Comment by blankjul** [comment]
Good point you both. To exactly avoid the division by zero, the following is added:

```
xu[xl == xu] = np.nan
```

which means if the values are the same then the ideal point is used but the nadir point is set to NaN. 
And if this is the case, we at least like to translate the current objective space in this dimension which means we take the difference between the ideal and the solutions. 

ideal == nadir -> NaN nadir -> only ideal -> translate
ideal+nadir -> translate and norm

I understand why this behavior can cause some confusion though. I am open to suggestions.

**Comment by jacktang** [comment]
Hello @blankjul ,

Now the running metric uses the nadir point from current `F`, and I think that's root cause of `ideal == nadir`. The nadir point should be set as the worst nadir point in the history solution(I call it g_nadir). Is it reasonable to you?

```
        F = algorithm.opt.get("F")
        c_F, c_ideal,  = F, F.min(axis=0)
        g_nadir = [max(history[k]["nadir"], history[k-1]["nadir"])  for k in range(1, len(history))] + [0.0]

        c_N = normalize(c_F, c_ideal, g_nadir)
        N = [normalize(e["F"], c_ideal, g_nadir) for e in history]
```

Regards
/Jack

**Comment by blankjul** [comment]
The nadir point needs to be updated over time. Setting it to the worst ideal point in history will cause issues. 

One way would be setting it to NaN for this dimension. Another would be setting it to the max in the current population only for the dimension where it is equal.

**Comment by blankjul** [comment]
Can you check if the commit above resolves the issue as well?

**Comment by jacktang** [comment]
> Can you check if the commit above resolves the issue as well?

Sure, I will test this in next days

> Setting it to the worst ideal point in history will cause issues.

Would you please talk about more about the related issue or share some resources about it? Thanks!

**Comment by blankjul** [comment]
Have you had a chance to test it yet?

That was a type above I wanted to say "Setting it to the worst **_nadir_** point in history will cause issues." The main reason is that the method is also used as a termination criterion. And you would always like to have the normalization being updated in each iteration. You can checkout our paper: `J. Blank and K. Deb. A running performance metric and termination criterion for evaluating evolutionary multi- and many-objective optimization algorithms` for more info.

**Comment by jacktang** [comment]
> Have you had a chance to test it yet?

Yes, and here is 860 generation running metric (terminated)

![g860_running-fixed](https://user-images.githubusercontent.com/44341/230879274-01e05c5a-013a-458a-9d0c-7d9dbe07edf1.png)

And also the running metric adopted "setting it to the worst nadir point in history"

![g860_running](https://user-images.githubusercontent.com/44341/230879773-07690983-8382-46dc-9955-983d2b771374.png)

**Comment by blankjul** [comment]
So did the commit solve the issue? If yes, can I close it?

**Comment by jacktang** [comment]
Yes, sorry for the later reply.
