### ISSUE TITLE
Maximization and Minimization

### ISSUE THREAD

**Issue by haritha-paul** [anyoptimization/pymoo#415]
Hi, the functions I need to optimize one is maximizing function and the other is  a minimizing function. How can we simulate this into the problem in pymoo?

If there's any idea on it, please let know.

Thanks in advance!

**Comment by jacktang** [comment]
@haritha-paul From the documentation (https://pymoo.org/getting_started/preface.html):

The objective function(s) 𝑓 are supposed to be minimized by satisfying all equality and inequality constraints. If a specific objective function is maximized (max𝑓𝑖), one can redefine the problem to minimize its negative value (min−𝑓𝑖).

**Comment by haritha-paul** [comment]
Thank you, will try that out!

**Comment by blankjul** [comment]
@jacktang Thanks!
