### ISSUE TITLE
Tkinter+matplotlib+multiprocessing integration documentation example

### ISSUE THREAD

**Issue by M4a1x** [anyoptimization/pymoo#416]
Hi there, great project!

As mentioned in #348 I spent quite some time getting `pymoo` work together with `tkinter`+`matplotlib`+`multiprocessing`. To help others I condensed down my current use case to a sort of ["minimum" working example that I put in this gist](https://gist.github.com/M4a1x/ff879aeca3812f5762ca52a44b2cd39d). 

Maybe this is helpful for others looking to do the same, or maybe someone finds a better way to do this. If you're interested you could include it somewhere in the documentation? I'm not an expert, so feel free to point out any mistakes.

**Comment by blankjul** [comment]
Looks cool! Yes, I definitely see some value in doing that! Especially together with interactive optimization e.g. NSGA-II with varying aspiration points this might be a good solution. 

Can you create a PR and create an ipynb file in the documentation folder? Feel free to be a little verbose and provide some details on how your code works and why this was important for you to code up.

I will then look at your PR and decide where it should be linked in the documentation.
