### ISSUE TITLE
Missing TypeHints and DocStrings across the code base 

### ISSUE THREAD

**Issue by Resethel** [anyoptimization/pymoo#419]
At the moment, it is somewhat non-trivial to understand how the code structures, and how the types flow through the code. Many classes and functions are missing docstrings clarifying their intent or the type of the inner variables, and there are almost no TypeHints across the code base.

TypeHints (see [PEP484](https://peps.python.org/pep-0484/)) make it easier to read and understand code (by default the "type" of objects in Python is dynamically determined and can change, adding TypeHints clarifies intent). Newer code that has been developed usually includes TypeHints.

I'd suggest using a tool such as [MonkeyType](https://github.com/Instagram/MonkeyType) to help with that process.

**Comment by blankjul** [comment]
Very good point. Mostly because the framework has historically not started with type hints. But I agree no reason to not start doing it. Also, let me know if you want to support us and join our team.

**Comment by Resethel** [comment]
I see !
I'd gladly help out. I can work on a PR for this issue

**Comment by blankjul** [comment]
Looking forward to your PR!

**Comment by gptlang** [comment]
Are there any updates? It's still quite painful working with pymoo due to the lack of types.
