### ISSUE TITLE
ValueError: bounds should be a sequence containing real valued (min, max) pairs for each value in x

### ISSUE THREAD

**Issue by balexx2** [anyoptimization/pymoo#428]
def optimize_data_rates(num_users, n_active_bs, P_max, Gamma_th, eta, carrier_frequency, max_distance, shadowing_std_dev, noise_power, antenna_gain):
            def objective(w_real_imag):
                w = w_real_imag[:n_active_bs * num_users] + 1j * w_real_imag[n_active_bs * num_users:]
                w = w.reshape(n_active_bs, num_users)
                satisfaction = eta * np.log(1 + np.sum(np.square(np.abs(np.transpose(np.conj(g)) @ w)), axis=0))
                penalty_power = 1e6 * np.maximum(0, np.sum(np.square(np.abs(w)), axis=1) - P_max)
                penalty_interference = 1e6 * np.maximum(0, np.array([sum([np.square(np.abs(np.sum(g[j, i].conj() * w[j, u] for j in range(n_active_bs)))) for u in range(num_users) if u != i]) - Gamma_th for i in range(num_users)]))
                return -np.sum(satisfaction) + np.sum(penalty_power) + np.sum(penalty_interference)
            
            g = calculate_channel_matrix(n_active_bs, num_users, carrier_frequency, max_distance, shadowing_std_dev, antenna_gain)
            #bounds = [(-10, 10)] * (2 * n_active_bs * num_users)
            n_variables = 2 * n_active_bs * num_users  # The number of variables being optimized
            bounds = [(-10, 10)] * n_variables  # Generate a pair of bounds for each variable

            result = differential_evolution(objective, bounds, maxiter=100, tol=1e-5)
            w_optimal = (result.x[:n_active_bs * num_users] + 1j * result.x[n_active_bs * num_users:]).reshape(n_active_bs, num_users)
            
            SINRs = np.array([np.square(np.abs(np.dot(g[:, i].conj().T, w_optimal[:, i]))) / (sum([np.square(np.abs(np.dot(g[:, i].conj().T, w_optimal[:, j]))) for j in range(num_users) if j != i]) + noise_power) for i in range(num_users)])
            data_rates = eta * np.log2(1 + SINRs)
            minimum_rate_requirements = np.maximum(0, data_rates - 1)
            
            return data_rates, minimum_rate_requirements

**Comment by blankjul** [comment]
please open a proper ticket with a description of the problem and not just (not even formatted) code.
