### ISSUE TITLE
Setting a starting solution in Pymoo does not work

### ISSUE THREAD

**Issue by PBerit** [anyoptimization/pymoo#429]
Hi all,

I want to use a starting solution for pymoo in the algorithms NSGA2. For that I have the following code

```
intial_solution = ICSimulation.simulateDays_ConventionalControl()
algorithm = NSGA2(
    pop_size=5,
    n_offsprings=2,
    sampling=FloatRandomSampling(),
    crossover=SBX(prob=0.7, eta=20),
    mutation=PM(eta=40),
    eliminate_duplicates=True
)
```

`algorithm.setup(problem, x0=intial_solution )`

So i just create an initial_solution by using an external file that returns an x vector that is the vector of decision variables in pymoo for the evalutation. Then I add algorithm.setup(problem, x0=intial_solution ). When adding this line, the algorithm does not seem to terminate or to generally show some outputs. Further, in the evaluation method I can clearly see, that the algorithm, even in the first iteration, does not use the inital_solution as all solutions in the first iteration are just randomly generated as if there is no inital_solution.

So I want to know, how can I tell pymoo to use the inital_solution as a good starting point for the optimization instead of just radomly initiallyzing the inital solutions?

**Comment by blankjul** [comment]
Please find a tutorial for population-based algorithms with a biased initialization here: https://pymoo.org/customization/initialization.html

**Comment by blankjul** [comment]
Could you resolve this issue?

**Comment by PBerit** [comment]
Thanks for your answers. Unfortunately, none of them seem to work. When I try the first approach (By Array approach)

```
intial_solution = ICSimulation.simulateDays_ConventionalControl()
algorithm = NSGA2(
    pop_size=10,
    n_offsprings=10,
    sampling = intial_solution ,
    crossover=SBX(prob=0.7, eta=20),
    mutation=PM(eta=40),
    eliminate_duplicates=True
)
```
Pymoo in fact uses the intial_solution but it does not vary it at all or just very slightly the first component of the vector and all others remain the same. This leads too only 1 Pareto-Optimal solution which is the starting solution which does makes applying NSGA2 and Pymoo pointless. 

When I try the second approach (By Population (pre-evaluated) approach) with the following code:
```
intial_solution = ICSimulation.simulateDays_ConventionalControl()

from pymoo.core.population import Population
from pymoo.core.evaluator import Evaluator
pop = Population.new("X", intial_solution )
Evaluator().eval(problem, pop)

algorithm = NSGA2(
    pop_size=10,
    n_offsprings=10,
    sampling = pop,
    crossover=SBX(prob=0.7, eta=20),
    mutation=PM(eta=40),
    eliminate_duplicates=True
)
```
I get the error message "Exception: Population Set Attribute Error: Number of values and population size do not match!"

I have to admit that I could not manage to try the approach from jacktang as it quite complex and I don't know how to apply it to my case. Is there not an easy option to include just one starting solution into the optimization process? In most of the other optimization frameworks you can do this with just one single line of code. But in Pymoo this does not seem to work.

**Comment by jacktang** [comment]
@PBerit , the `HybridSampling` code

```
import numpy as np
from pymoo.core.sampling import Sampling
from pymoo.operators.sampling.rnd import FloatRandomSampling


class HybridSampling(Sampling):
    
    def __init__(self, base_sampler=None, candidates=None):
        """Sampling class that uses candidate solutions

        Parameters
        ----------
        base_sampler : Sampling | None, optional
            Base pymoo sampler. If None, uses FloatRandomSampling, by default None
            
        candidates : numpy.array | None, optional
            Candidate solutions, by default None
        """
        super().__init__()
        if base_sampler is None:
            base_sampler = FloatRandomSampling()
        self.base_sampler = base_sampler
        
        self.candidates = candidates
        if self.N > 0:
            self._do = self._do_replace
        else:
            self._do = self.base_sampler._do
    
    @property
    def N(self):
        if self.candidates is None:
            return 0
        else:
            return np.shape(self.candidates)[0]
    
    def _do_replace(self, problem, n_samples, **kwargs):
        
        candidates = np.array(self.candidates)
        if np.shape(candidates)[1] != problem.n_var:
            raise ValueError("Candidates must have dimension equals n_var on axis=1")
        else:
            pass
        
        if n_samples == self.N:
            return np.array(self.candidates)
        else:
            X = self.base_sampler._do(problem, n_samples, **kwargs)
            
        if n_samples < self.N:
            reps = np.random.choice(self.N)
            X = np.array(self.candidates)[reps]
        else:
            X[:self.N, ...] = np.array(self.candidates)
    
        
        return X
```

and instance the sampling method
```
sampling=HybridSampling(candidates= intial_solution)
```

Hope it helps!

**Comment by PBerit** [comment]
@jacktang : Thanks for your answer. I have to admit that I don't understand your code at all. I just want to set the starting solution for the optimization process with NSGA2 (or any other population based metaheuristic). I don't want something like Hybrid Sampling. So is there no way in Pymoo to just tell Pymoo to use a starting solution. Unfortunately, the link from [blankjul](https://github.com/blankjul) does not help (see my answer above).

**Comment by PBerit** [comment]
@cyrilpic : Thanks for your answer. I can't create more solutions but just the one conventional solution. Unfortunately when doing what you suggested to use the code from Jack and then use your suggested code, I get an error message "IndexError: tuple index out of range" thrown by the line of Jack's code "if np.shape(candidates)[1] != problem.n_var:". "problem.n_var" is an int with the value 48 and the dimensionality of "candidates" is (48,)

**Comment by cyrilpic** [comment]
It seems like `intial_solution` must be a 2D array: you should probably pass it as `HybridSampling(candidates=[initial_solution])`.

**Comment by PBerit** [comment]
@cyrilpic : Thanks for your answer. Now I don't get an error message. However, the results are quite bad. Pymoo does not find any other pareto optimal solution except for the initail solution altough there are many many other pareto optimal solutions that are also easy to find. So I assume something is still not working properly when setting the initial solution.

**Comment by jacktang** [comment]
Hello @PBerit, back to the original question: why did you select initial_solution(s)? are they feasible? if yes, how do you know they are feasible?

**Comment by PBerit** [comment]
@jacktang : Thanks for your answer jecktang.In fact, the initial solution that I choose is a feasible one. Actually my problem is a sheduling problem for controlling the power output of a heating device. I create the initial solution by just using a conventional control approach that is by far not optimal. So the optimization has to come up with better solutions than the inital solution. When not choosing the inital solution for the optimization in NSGA2 and Pymoo, the results are even worse than the initial solution (which makes sense to some degree as I have 48 continuous decision variables). But when having the initial solution as a starting point, NSGA2 should be able to improve it as far as I understand.

**Comment by jacktang** [comment]
@PBerit , yes you are right. If you want better solution, don't forget to adjust values in termination which will takes longer time to get the high quality solutions. Or providing better new start point. Hope it helps!

**Comment by jacktang** [comment]
> it does not find a better solution than the inital solution provided 
I am very double about that. How do you compare those solutions? By the objective functions value? if yes, can you print the objective function values?

> Maybe the cause of the problem is, that I only provide 1 starting solution (I can't provide more) and all other solutions in the first population are just random solutions that are all extremely bad.
Did you turn on the process display? if yes, could you please paste the result on the thread? 

Meanwhile, please provide more information about the problem, say N objectives, 48 continuous decision variables, N eq-consts, N ieq-consts.

**Comment by jacktang** [comment]
The possible reason  I know is the optimization is terminated while cv_avg > 0, the case may refer to https://github.com/anyoptimization/pymoo/issues/434

**Comment by PBerit** [comment]
@jacktang : Thanks Jack for your answer and effort. I really appreciate it. I now get better solutions as I increased the population and offspring size. I have now the following code:

```
algorithm = NSGA2(
    pop_size=100,
    n_offsprings=100,
    #sampling=FloatRandomSampling(),
    sampling=HybridSampling(candidates=[initial_solution_conventional_control]),
    crossover=SBX(prob=0.7, eta=20),
    mutation=PM(eta=40),
    eliminate_duplicates=True
)
```
You see that I use the 3 parameters "    crossover=SBX(prob=0.7, eta=20), mutation=PM(eta=40),". How can I optimally choose them? Any advice for that?

**Comment by jacktang** [comment]
> You see that I use the 3 parameters " crossover=SBX(prob=0.7, eta=20), mutation=PM(eta=40),". How can I optimally choose them? Any advice for that?

@PBerit , it is ok to keep the default value. If you want better solution, tune the parameters in termination.

**Comment by PBerit** [comment]
Thanks for your answer Jack. How can I get to know the default parameters? And is there any built-in search strategy in Pymoo that determines the best parameters based on several runs of an algorithm?

**Comment by jacktang** [comment]
> Thanks for your answer Jack. How can I get to know the default parameters? 
The code : https://github.com/anyoptimization/pymoo/blob/main/pymoo/termination/default.py

**Comment by PBerit** [comment]
@jacktang : Thanks Jack for your answer. I don't understand what the link you posted should be used for. I wanted to know what the default parameters are for  "crossover=SBX(prob=0.7, eta=20), mutation=PM(eta=40)". I don't see anything related in the code.

**Comment by jacktang** [comment]
@PBerit Sorry for the misunderstood your question. You can check the default parameters in `nsga2` algorithm here: https://github.com/anyoptimization/pymoo/blob/566a3d7af9cc78772a2744f61b0cf78fa3f1fe2f/pymoo/algorithms/moo/nsga2.py#L90

**Comment by PBerit** [comment]
Okay, thanks a lot @jacktang for your great help. I really appreciate it.
