### ISSUE TITLE
Is pymoo meant only for population based-search algorithms?

### ISSUE THREAD

**Issue by Leviathan321** [anyoptimization/pymoo#430]
I was wondering whether pymoo is only meant for developing population-based search algorithms, as you do not provide simulated annealing or gradient descent (e.g., supported by jMetalPy). We are using pymoo for research, and was thinking about to use the internal  data structures to implement non population based algorithms. 
I am not sure if this is correct, and whether we should use such hack as this might be not part of the vision of pymoo.

**Comment by blankjul** [comment]
We would be more than happy to also have some more non-population-based algorithms in there. So far it is only `PatternSearch` and  `NelderMead` (technically it has also a small population, but not in an EA sense).

**Comment by blankjul** [comment]
Would you be interested in implementing some and contributing?

**Comment by blankjul** [comment]
Already looking forward to your PR! Feel free to post the paper (or pre-print) here as well.
