### ISSUE TITLE
How to improve pymoo performance?

### ISSUE THREAD

**Issue by jacktang** [anyoptimization/pymoo#431]
Hello, there!

I've applied pymoo framework to the real problem in industry. The problem has 2 objective functions, 123 variables and 2425 ieq_constraints, and I set the population size to 200 and n_offsprings to 150. The optimization take around 1103 seconds and 899 generation(134899 evaluations). My goal is to get the result in 200 seconds.
I’ve parallelized the problem using 20 multi-process, the machine has 24 i9 cores.
I inspected the profile using py-spy and attached the result. 

You can download the svg and it is interactive chart: https://github.com/anyoptimization/pymoo/assets/44341/305c3c06-2831-44d9-840c-079759823211, and can you please give me some advice on improving pymoo performance? 

![xx-profile](https://github.com/anyoptimization/pymoo/assets/44341/305c3c06-2831-44d9-840c-079759823211)

Thanks!
/Jack

**Comment by jacktang** [comment]
From above diagram, the 7th row shows that 78% time spends on reduction#dumps. So the program is busy at copy data from one process to another? If yes, could you please tell me what code occur the data copying. Thanks!

**Comment by jacktang** [comment]
Well, I think there are some options to improve the problem.

1. Improve the `ForkingPickler` module in `multiprocessing` using faster serialization/deserialization lib
2. Use shared memory in multi-process mode for the processes communication.

**Comment by blankjul** [comment]
Can you check if custom parallelization resolves the issue? https://pymoo.org/problems/parallelization.html#Custom-Parallelization

Basically, you can implement your parallelization technique entirely yourself using this method.
Please let me know if this works better.

**Comment by jacktang** [comment]
@blankjul Thanks for the reply! I've tried joblib and it improve a little bit. Also I want to try shared memory for multi-process, and could you please tell me where the mutli-process communicate with each other?

**Comment by cyrilpic** [comment]
Hi Jack,
Parallelization is always quite tricky and I recommend that you do some tests with "fake" problems (problems that do nothing expensive but have a `time.sleep(10)` so that you can better control what is spent in computation vs communicating.
Communication is a bottleneck for parallel computing and pymoo often sends the whole `problem` every time to the sub-processes, which can be memory-intensive depending on how you have set it up.
Dask also has a nice profiling interface if you want to have a better insight into what is going on.

**Comment by jacktang** [comment]
@cyrilpic Thanks for the suggestion! I'll try it later.

**Comment by jacktang** [comment]
On the same machine, I tried both Dask and Joblib. And Joblib improved a little, since the Loky backend is faster than pickle in object serialization/deserialization. see: https://joblib.readthedocs.io/en/latest/auto_examples/serialization_and_wrappers.html, and Dask is slow in the localcluster mode on the same machine, and I found that the serialization backend is the multiprocessing/pickle also.

**Comment by cyrilpic** [comment]
What I meant is that Dask has a dashboard (localhost:8787 when a `LocalCluster` is running), where you can monitor what is going on (including the size of what is being passed between processes). This may help you understand what is going on.

I do multiprocessing with pymoo all the time and it is fast (I use Dask), but I worked on making the `Problem` class as light as possible. So, it is not per se a pymoo issue.

**Comment by jacktang** [comment]
@cyrilpic I agree with you when the `Problem` is light and the performance is good (if you use joblib, it could much faster).
