### ISSUE TITLE
Multiple termination criteria

### ISSUE THREAD

**Issue by craftsmanhe** [anyoptimization/pymoo#433]
Hi,

I am using pymoo GA algorithm to do a discrete optimization.

And I want to set multiple termination criteria.

(1). I want to set a termination on the `out["F"]`. The minimum value of my cost function is 0. So if any population at any generation gives a 0 in `out["F"]`, the GA algorithm will terminate and return the `res.X` giving the value 0.

(2). I want to set a termination on time. I saw that there is a function and I can set like `get_termination("time", "00:10:00")` for running 10 minutes. But I want to incorporate both (1) and (2).

(3). The minimum difference among my cost function is 1. I am wondering if I should also set `ftol=1` somewhere?

Thanks.

**Comment by blankjul** [comment]
Checkout this example: https://github.com/anyoptimization/pymoo/blob/main/examples/termination/multiple.py

You can define each of your termination criteria and feed it into `TerminateIfAny`. Does that work for you?

**Comment by craftsmanhe** [comment]
Thanks a lot.

(1) Can you give me an example on self defining the termination criteria by a function like `myselfTermination(*args, **kwargs)`? If I used this `myselfTermination(*args, **kwargs)` in GA, what should be the input and output?

(2) `TimeBasedTermination(0.2)` is the same as get_termination("time", "00:00:12")?  `0.2` mean '0.2' minutes?

(3) If the minimum difference among my cost function is 1. Does set `ftol=1` somewhere necessary?

Thanks
