### ISSUE TITLE
ModuleNotFoundError: No module named 'pymoo.termination'

### ISSUE THREAD

**Issue by dovahkiin0022** [anyoptimization/pymoo#435]
While trying to run a multi objective optimization problem, I ran into this particular issue - 

```
from pymoo.termination.default import DefaultMultiObjectiveTermination

termination = DefaultMultiObjectiveTermination(
    xtol=1e-8,
    cvtol=1e-6,
    ftol=0.0025,
    period=30,
    n_max_gen=1000,
    n_max_evals=100000
)
```

ModuleNotFoundError                       Traceback (most recent call last)
 in 
----> 1 from pymoo.termination.default import DefaultMultiObjectiveTermination
      2 
      3 termination = DefaultMultiObjectiveTermination(
      4     xtol=1e-8,
      5     cvtol=1e-6,

ModuleNotFoundError: No module named 'pymoo.termination'

**Comment by blankjul** [comment]
Are you using `pymoo==0.6.0.1`?

(the import has changed in the more recent versions)
