### ISSUE TITLE
[Feature Request] Support parallelization on Ray

### ISSUE THREAD

**Issue by zhiruiluo** [anyoptimization/pymoo#438]
[Ray](https://docs.ray.io/en/latest/index.html) is an open-source unified framework for scaling AI and Python applications. It provides the compute layer for parallel processing so that you don’t need to be a distributed systems expert.

**Comment by zhiruiluo** [comment]
I spent some time made an experiment using Ray as backend to parallize pymoo. Here is an example:
```python
import ray

class RayParallelization:
    def __init__(self, job_resources={}) -> None:
        super().__init__()
        self.job_resources = job_resources

    def __call__(self, f, X):
        runnable = ray.remote(f.__call__.__func__)
        runnable = runnable.options(**self.job_resources)
        futures = [runnable.remote(f,x) for x in X]
        return ray.get(futures)

    def __getstate__(self):
        state = self.__dict__.copy()
        return state

def main():
    ray.init()
    runner = RayParallelization(job_resources={'num_cpus':8, 'num_gpus': 1})
    problem = get_problem()
    algorithm = get_algorithm()
    res = minimize(problem, algorithm, ('n_gen', 10), seed=1)

main()
```

If there is any suggestion or better way, I'd love to hear it.

**Comment by zhiruiluo** [comment]
I am more than happy to make an PR for this feature request.

**Comment by blankjul** [comment]
Looking forward to your PR!

Can you put the import statement in the method itself? At this point I would prefer to avoid a dependency on Ray to install pymoo.

**Comment by zhiruiluo** [comment]
> Can you put the import statement in the method itself? At this point I would prefer to avoid a dependency on Ray to install pymoo.

Thanks for pointing this out, @blankjul. I will add this in the PR.
