### ISSUE TITLE
i get you code,but i can not use it,even i read your web(https://pymoo.org/index.html)

### ISSUE THREAD

**Issue by qq272574497** [anyoptimization/pymoo#439]

**Comment by blankjul** [comment]
Please provide some more details when opening an issue. Even the title does not provide any identification what error you are facing.

**Comment by qq272574497** [comment]
i get your code,but i do not know how to use it

**Comment by blankjul** [comment]
I recommend before using pymoo to learn the basics of Python, and then the corresponding widely used scientific libraries such as Numpy.
