### ISSUE TITLE
Discrepancy in DTLZ5 definition

### ISSUE THREAD

**Issue by thchang** [anyoptimization/pymoo#449]
The definition of DTLZ5 in the source code:

https://github.com/anyoptimization/pymoo/blob/main/pymoo/problems/many/dtlz.py#L131

does not match the definition in the documentation:

https://pymoo.org/problems/many/dtlz.html#DTLZ5

Specifically, there is an additional factor of $\pi / 2$ in the definition of $\theta$ in the documentation, that doesn't appear in the implementation.

I believe that the code is correct and the documentation is wrong, since I had implemented my own variation of ``DTLZ5`` here, following the definition in the docs and when I ran it, I did not recover the correct Pareto front:

https://github.com/parmoo/parmoo/blob/main/parmoo/simulations/dtlz.py#L639

I deleted a factor of $\pi / 2$ from my definition of $\theta$ so that it matches your source code, and that made the issue go away.  Probably not an urgent issue, but just bringing this to your attention in case it helps!

**Comment by blankjul** [comment]
Thanks for pointing this out! I am pretty sure that the function is correct (I have checked correctness against the original C code while implementing it). Can you create a PR to make the documentation to fix the documentation issue?

Thank you in advance!
