### ISSUE TITLE
hyperparameters optimization for optimization methods that do have defined hyperparameters

### ISSUE THREAD

**Issue by yeodynasty** [anyoptimization/pymoo#453]
Hi,
for those optimization methods that do not have their hyperparameters defined, may I ask how do we provide them when initializing HyperparameterProblem?

I tried the following but it doesn't work.

Any guidance will be greatly appreciated!

--------
from pymoo.core.parameters import set_params, hierarchical
from pymoo.optimize import minimize
from pymoo.core.mixed import MixedVariableGA

varsDict= {
    "n_offsprings": [42, 48, 56, 64],
    "model": ["1.0 / 7.0"],
    "gamma": [0.7, 0.75, 0.8, 0.85, 0.95],
    "alpha": [0.1, 0.2, 0.3, 0.4]
}
res = minimize(**HyperparameterProblem(algorithm, performance, vars=varsDict)**,
               MixedVariableGA(pop_size=24),
               ("n_gen", 50),
               seed=1,
               verbose=True)

hyperparams = res.X
print(hyperparams)
set_params(algorithm, hierarchical(hyperparams))

**Comment by blankjul** [comment]
For your own methods it is probably easier to directly use the mixed variables feature: https://pymoo.org/customization/mixed.html

Could be something like the code below:

```from pymoo.algorithms.hyperparameters import SingleObjectiveSingleRun
from pymoo.algorithms.soo.nonconvex.es import ES
from pymoo.core.mixed import MixedVariableGA
from pymoo.core.problem import ElementwiseProblem
from pymoo.core.variable import Integer, Choice
from pymoo.optimize import minimize
from pymoo.problems.single import Sphere

problem = Sphere(n_var=10)
n_evals = 500

performance = SingleObjectiveSingleRun(problem, termination=("n_evals", n_evals), seed=1)


class MixedVariableProblem(ElementwiseProblem):

    def __init__(self, **kwargs):
        vars = dict(
            n_offsprings=Integer(bounds=(20, 100)),
            rule=Choice(options=[1.0 / 7.0, 2.0 / 7.0]),
            phi=Choice(options=[1.0, 2.0, 3.0]),
        )
        super().__init__(vars=vars, n_obj=1, **kwargs)

    def _evaluate(self, x, out, *args, **kwargs):
        algorithm = ES(**x)
        v = performance(algorithm)
        out.update(v)


res = minimize(MixedVariableProblem(),
               MixedVariableGA(pop_size=5),
               termination=('n_evals', 50),
               seed=1,
               verbose=True)

hyperparams = res.X
print(hyperparams)
```
