### ISSUE TITLE
Hyperparameter Optimization over multiple training problems and Automatic Design of Multi-Objetive Algorithms

### ISSUE THREAD

**Issue by MLopez-Ibanez** [anyoptimization/pymoo#456]
Usually one wants to optimize hyper-parameters over a set of training problems ([Automatic Configuration of Multi-objective Optimizers and Multi-objective Configuration](http://doi.org/10.1007/978-3-030-18764-4_4)). This doesn't seem to be supported?

For applications of this approach see: 

 * [Automatic Configuration of NSGA-II with jMetal and irace](http://doi.org/10.1145/3319619.3326832).
 * [Automatically Designing State-of-the-Art Multi- and Many-Objective Evolutionary Algorithms](http://doi.org/10.1162/evco_a_00263).
 * [Automatic Component-Wise Design of Multi-Objective Evolutionary Algorithms](http://doi.org/10.1109/TEVC.2015.2474158). 

I'm happy to modify [iracepy](https://github.com/auto-optimization/iracepy) as needed to support this but it seems pymoo needs some modifications as well.

**Comment by blankjul** [comment]
Hey, I was not even aware of iracepy! Cool that there also is a Python version of it. Is it an entire reimplementation of the original R package?

I would be more than happy to have another hyperparameter algorithm available.  I have just posted this example here:
https://github.com/anyoptimization/pymoo/issues/453
which is more flexible in redefining the evaluation.

The evaluation class `SingleObjectiveSingleRun` would need to be replaced by evaluating a configuration on a whole suite of problems. 

Is there any way I can help integration irace into pymoo for that?

**Comment by blankjul** [comment]
I will close this issue for now. 

I would be more than happy to look at a PR showcasing how we could integrate it (maybe that would be a cool project for a student you supervise?).
