### ISSUE TITLE
GPU to evaluate the optimization problem

### ISSUE THREAD

**Issue by jacktang** [anyoptimization/pymoo#460]
Hello,

I want to add GPU to evaluate the optimization problem (twice :)), my idea is keeping current pymoo multi-process architecture, but replacing `StarmapParallelization` with `PytorchParallelization`/`JAXParallelization`, and calculate the optimzation problem using pytorch/JAX. I created one demo, but found that the performance is slower than `JoblibParallelization`. Any idea or suggestion?

Regards
/Jack

**Comment by blankjul** [comment]
When using pytorch you probably want use tensors. This is then the parallelization method mentioned as vectorized here:
https://pymoo.org/problems/parallelization.html#Vectorized-Matrix-Operations

You can take the numpy matrix, create a pytorch tensor, do the operation, and then put results back to a numpy matrix.
Note, that this will only speed up things if that this does not introduce more overhead than the expensiveness of the calculations.

**Comment by jacktang** [comment]
Thank you for the kindly suggestion! @blankjul. Now the demo problem works and the performance is boosting 🚀 .
