### ISSUE TITLE
cannot import name 'default_termination' from 'pymoo.optimize'

### ISSUE THREAD

**Issue by lampda** [anyoptimization/pymoo#462]
Hi,

I got this error while trying to import default_termination.
And I tried pymoo=0.3.0 and the 0.6.0.* , but all failed.

Updated: this issue is related to pysamoo==0.1.1 and pysamoo of this version will require pymoo-0.6.0 to be installed in my docker image (official image: jupyterhub:3) where python is of version 3.10.

Could you give me any suggestion?

**Comment by blankjul** [comment]
Unfortunately, I have never found the time to update pysamoo to the newest pymoo version. 

Can you please try with Python 3.9 and pymoo version (pip install pymoo==0.6.0.dev0) and see if that works for you?

**Comment by lampda** [comment]
thank you for the reply.

It seems OK without error for 'default_termination'. `python==3.9.17 and pymoo==0.6.0.dev0`
Previously the error came from this line:

```
from pysamoo.algorithms.gpsaf import GPSAF
```
and now I got another error, see this #470 .

I close this issue since this importing error is solved.
