### ISSUE TITLE
Custom crossover operator for Custom Variable Types 

### ISSUE THREAD

**Issue by abuliga** [anyoptimization/pymoo#479]
Hi!

I had a question regarding the https://pymoo.org/customization/custom.html implementation. When creating a custom Crossover operation for a single type of variables, say Choice, will each of the variables belonging to this type be used in an ElementWiseProblem?

As of now, when I try to implement it, the problem I define in the minimize() function is not used any more in the _do and a new Problem object is created that takes a single attribute at a time.

Is this by design or a bug I came across? Thanks!

**Comment by blankjul** [comment]
Sorry for the late reply. Are you still running into this issue? Can you provide a code example? I am not sure if I can follow your description. 

All variables should be provided to `ElementwiseProblem`. If no this seems to be a bug.
