### ISSUE TITLE
Variable specification for a mixed integer MOO problems in pymoo

### ISSUE THREAD

**Issue by fzm1108** [anyoptimization/pymoo#480]
Hello, I have a question about the specification of mixed integer MOO problem. When I used the method given in the example on https://pymoo.org/customization/mixed.html (Multi-objective Optimization With Mixed Variables), to design my MOO problem, python given the error:   
" return distance.cdist(A.astype(float), B.astype(float), **kwargs)  
TypeError: float() argument must be a string or a real number, not 'dict'". 

So, how to fix this error? Otherwise, how to speficied mixed variable for a relatively large MOO problem? Many thanks for your reply.

**Comment by jacktang** [comment]
> " return distance.cdist(A.astype(float), B.astype(float), **kwargs)
> TypeError: float() argument must be a string or a real number, not 'dict'".

Hello @fzm1108 , the error means A/B should be a real number, but now some are dict(s). And can you please paste the definition of your optimization problem?
