### ISSUE TITLE
Bug in gaussian mutation operator

### ISSUE THREAD

**Issue by mpds** [anyoptimization/pymoo#481]
Hi, I believe there's a bug in the gaussian mutation operator. In [this line](https://github.com/anyoptimization/pymoo/blob/7d63118def98eeb078d6d6e2f61e80e3f4cc8bea/pymoo/operators/mutation/gauss.py#L28C1-L28C1), the `scale` parameter of the [`np.random.normal`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html) function can be negative depending on the problem's upper and lower bounds (negative values are not allowed for stdev). Maybe the intended behavior was: 
```python
np.random.normal(X[mut], sigma * abs(_xu - _xl))  # instead of (_xu * _xl) here
```

**Comment by blankjul** [comment]
Good catch! I just pushed a commit with a fix.
