### ISSUE TITLE
Termination criteria

### ISSUE THREAD

**Issue by faranak1991** [anyoptimization/pymoo#491]
Hello,

I want to define a termination criteria that will end it when the objective function reaches a certain threshold. I've consulted the manual, but I'm still uncertain about how to set this termination criterion. Any assistance on this matter would be highly valued ?

Thanks

**Comment by blankjul** [comment]
Yes, this is possible. The algorithm is terminated when progress (which is returned by `_update`) equals `1.0`. If you don't care about the progress made you can simply return `0.0` if above your value and `1.0` if equal or below.

```
from pymoo.algorithms.soo.nonconvex.de import DE
from pymoo.core.termination import Termination
from pymoo.optimize import minimize
from pymoo.problems.single import Sphere

problem = Sphere()

algorithm = DE()


class MyTermination(Termination):

    def __init__(self, value) -> None:
        super().__init__()
        self.value = value

    def _update(self, algorithm):
        f_min = algorithm.opt.get("f").min()
        return 1.0 if f_min <= self.value else 0.0


termination = MyTermination(0.01)

res = minimize(problem,
               algorithm,
               termination=termination,
               seed=1,
               verbose=True)

print(f"Best solution found: \nX = {res.X}\nF = {res.F}\nCV= {res.CV}")

```
