### ISSUE TITLE
Printing vs Logging

### ISSUE THREAD

**Issue by CompRhys** [anyoptimization/pymoo#492]
When we excute pymoo it currently runs in a process that doesn't flush to stdout until it completes, this makes it hard to track progress through our executor. Are there any possibilities of being able to pass a logger to methods where the code would then use the logger rather than printing output?

**Comment by blankjul** [comment]
How do you run your code? Is redirecting the output with the `>` in the command line an alternative for you?

Another way is when running an optimizer redirecting the output within Python. (e.g. with a framework like this. https://github.com/sloisel/streamcapture).

I have never tried it myself. But would be curious if this helps. It would be great if you could let others and me know here in this issue.
