### ISSUE TITLE
Use Dominance Degree Matrix for NDS

### ISSUE THREAD

**Issue by gresavage** [anyoptimization/pymoo#495]
Recently, an algorithm for non-dominance sorting has been proposed called Dominance Degree Approach for Non-Dominated Sorting (see: [DDA-NS](https://ieeexplore.ieee.org/document/7469397)). In the worst case, this algorithm can conduct the sort in $O(MN\log N)$ time in terms of objective function value comparisons which is a vast improvement over the typical $O(MN^2)$. A thorough empirical comparison of NDS algorithms upholds this result, see [here](https://www.aimsciences.org/article/doi/10.3934/jimo.2020009)

It would be a great addition to the current suite of NDS algos provided by Pymoo.

**Comment by blankjul** [comment]
Thank you for referring to a new paper here! Always good to be up to date!

Did the authors publish the code as well? If yes what programming language? If not, would be be interested in implementing it and contributing to pymoo?

**Comment by gresavage** [comment]
My pleasure! Unfortunately I could not find the code from the original authors - however I did find related work which implemented DDA-NS and provided their own novel method, DDA-ENS in C++ [here](https://github.com/rsenwar/Non-Dominated-Sorting-Algorithms)

I would be willing to implement this, as well as (eventually) the DDA-ENS in python. I'm no computer scientist, though, so it will take some time to interpret the C++ code and merge it with my understanding of DDA-NS.

Another alternative is to simply bind the C++ libraries, with the authors' permission of course - to python but it doesn't look pymoo currently uses a mixed-language approach and it would complicate the bug support process.

**Comment by gresavage** [comment]
I may have overestimated the complexity when I said it might take me a while :laughing:

I believe I have it fully implemented. I haven't compared with with the logic in the C++ from the DDA-ENS paper repo. I implemented it inside of another project I'm working on in a private repo so today or tomorrow I will fork pymoo and move the code over.

Also worth noting is that I implemented it using `np.argsort` on the objective function values. This means that there is no incorporation of constraint variables. To do so would take considerable more effort and thought for a number of reasons - most obvious of which is that `numpy` does not provide a way to pass a custom ordering function to the sort functions and thus I would need to determine a clean solution using `np.vectorize` or similar in order to minimally-impact speed. Second most obvious is that since the authors didn't directly address constraint variables I would need to think deeply about how they fit into the DDA-NS methodology.

**Comment by blankjul** [comment]
Great! You can integrate it with pymoo directly and then write your unit tests there (you can check that it returns the same results as the other implementations that already exist). It would also need to have some comparison of the methods based on efficiency (measured by wall-clock time).

For now, I think you can just assume no constraints (all other implementations in pymoo do this too). 

Please keep me posted. Looking forward to your PR.

**Comment by gresavage** [comment]
Perfect!

I just pushed the pure python and cython implementations to my [fork](https://github.com/gresavage/pymoo). I confirmed it produces the same results as the existing methods.

I will work on the unit tests and timing tests now

**Comment by gresavage** [comment]
@blankjul so I have the tests implemented and everything passes. However comparing the algorithm times shows that both DDA-ENS and DDA-NS are *slower* than the other algorithms, at least in Cython.

I'm fairly certain this is just because I have not implemented them efficiently in Cython. When I time the algorithms in pure C++ I find the behavior I expect - both perform faster than Fast NDS. I'm pretty sure the crux of the bottleneck is in the construction of the comparison and dominance degree matrices.

Attached is the timing graphs for the pure C++ implementation - ignore the Julia/Python stuff, I reused the timing and graphing code from another investigation I was doing lol. Each point in the graph is based on 1000 samples, `population` refers to the population size $N$ being sorted.

![fast_ns_time](https://github.com/anyoptimization/pymoo/assets/7985947/3afc7722-be43-48f0-b738-5da360cd38c8)

**Comment by gresavage** [comment]
For reference here is the same test using the timing results with the Cython code I implemented, also 1k samples / data point
![Uploading algo_time.png…]()

**Comment by gresavage** [comment]
Here is the timing test with the Cython code - also 1k samples per point
![algo_time](https://github.com/anyoptimization/pymoo/assets/7985947/aed00db0-c210-426d-9a31-da77ab48d411)

**Comment by blankjul** [comment]
Thanks for the detailed answer and comparison! 

I had a quick look at your fork and implementation. You can use this command `cython -a non_dominated_sorting.pyx` to compile an HTML file (see screenshot attached) which helps you to detect bottlenecks in your code. Basically, everything that is yellow is not that efficient.

![dda-ns](https://github.com/anyoptimization/pymoo/assets/10279009/96643f4c-51b8-48dd-a499-0d97775372f4)

Do you want to try to remove the bottlenecks and see if this improves the performance?

An alternative by the way is including CPP code directly.  Check out the `cython/vendor` folder for that.

**Comment by gresavage** [comment]
Beautiful! Thanks for your input. This will definitely prove helpful

Fortunately I already have a C++ implementation at-hand so if I can't speed it up in cython I will just call the C++ routine.

**Comment by gresavage** [comment]
Your guidance certainly helped, thank you.

**Good news**: I was able to vastly improve the speed of the algos in python so now the results are indeed faster than Fast NDS.

**Bad news**: I was only able to gain mild improvements in Cython, though I've isolated the bottleneck primarily to the in-place addition operation over the $N\times N$ dominance degree and comparison matrices. It's not this way on the branch, but I broke each section into a separate function and then profiled it with cProfile to hunt that issue down.

I've tried a variety of methods to improve the speed here but so far the fastest is still simply looping over each element one-by-one, since we are able to also reset the comparison matrix to zeros in the process. Thus preventing another pass over the entire matrix. FWIW I studied mechanical engineering so I don't have the depth of knowledge of a computer scientist to be able to know what C/C++ practices would help here.

Results for sweeps over # of objectives and # of solutions are attached, 100 samples per data pt.

![algo_time_3](https://github.com/anyoptimization/pymoo/assets/7985947/3c7f6fc8-bfc3-44e5-aa1b-2f3163c67623)
![algo_time_2](https://github.com/anyoptimization/pymoo/assets/7985947/fe390948-d76c-49bb-8838-1a2a1b28f98d)

**Comment by blankjul** [comment]
How do you create the population to test it on? Have you compared the runtime of an algorithm using it during a run? (I think this is what ultimately would be my criterion to make a decision). Can you also add Best-Order-Sort in there? (I have implemented this a while ago because it was proposed by a former lab mate).

**Comment by gresavage** [comment]
I generate the population the same way it is done in testing: an `np.ndarray` of random floats with a random seed, the only difference being that I don't set the zero-th objective to ones.

I have used both `time.perf_counter` and `timeit.timeit` on *just* the call to the sort strategy (e.g. `timeit(f'nds(F, strategy={strategy})', globals = {**globals(), "nds": fn, "F": test_set}, number=1)`) for each sample point... so no setup time is included in the results.

I'll run it on some of the benchmark problems to see how it performs in-the-loop and report back

**Comment by gresavage** [comment]
So here are the "comprehensive" results sweeping the # of objectives and population size using various sort algos.

Problem: DTLZ2 (n_var = 7 + n_obj)
Genetic Algorithm: NSGA-II
Stopping Criterion: `n_gen == 10`
Random Seed: 1
Samples / Data Point: 10

![DTLZ2_obj_time](https://github.com/anyoptimization/pymoo/assets/7985947/b6b45e47-34d8-4e21-b7c6-df30e630b00b)
![DTLZ2_time](https://github.com/anyoptimization/pymoo/assets/7985947/215ffc7f-94cd-4999-bfe8-6fdc40581e29)

**Comment by blankjul** [comment]
Am I concluding this right that Best-Order-Search seems to be the fastest?
Even if I would still be happy to include your code by the way.

**Comment by gresavage** [comment]
That's what I am seeing as well

I'm honored! Then I will make some finishing touches and open a PR to merge my fork

**Comment by blankjul** [comment]
Great! Thank you in advance!
