### ISSUE TITLE
MultiObjectiveSpaceTermination - tol parameter

### ISSUE THREAD

**Issue by AndSalaMove** [anyoptimization/pymoo#498]
Hi,
If there is the case in which Multi-objective optimization runs on two quantities that span over different orders of magnitude, I reckon it would be more appropriate to pass a vector as the `tol` parameter. 
To check for termination, the algorithm should check `if [f1, f2, ..., fn] < [tol1, tol2, ..., toln]`.
Any opinions on this?

**Comment by blankjul** [comment]
If you use `DefaultMultiObjectiveTermination` then `ftol` already refers to the normalized objective space.
Please see `https://ieeexplore.ieee.org/document/9185546` for more details.
