### ISSUE TITLE
AttributeError: 'Result' object has no attribute 'time'

### ISSUE THREAD

**Issue by MidnightBiscuit** [anyoptimization/pymoo#507]
According to documentation (https://pymoo.org/interface/result.html) the minimize function can return the execution time, but I have the error 'AttributeError: 'Result' object has no attribute 'time' ' when I replicate the method in the doc.

Here small code snippet : 
```python
problem = MyProblem()

algorithm = NSGA2(
    pop_size=40,
    n_offsprings=10,
    sampling=FloatRandomSampling(),
    crossover=SBX(prob=0.8, eta=15),
    mutation=PM(eta=20),
    eliminate_duplicates=True
)

termination = get_termination("n_gen", 10)

res = minimize(problem,
               algorithm,
               termination,
               seed=1,
               save_history=True,
               verbose=True
)

print(f'Time elapsed for minimisation: {res.time:.2f} s')
```

**Comment by blankjul** [comment]
Thanks for reporting. It is in fact `exec_time`.

I have updated the documentation in the commit above. It will update once a new version is released.
