### ISSUE TITLE
Same issue as #368  in the new version about label of some variables

### ISSUE THREAD

**Issue by NatOnera** [anyoptimization/pymoo#508]
The test provided for issue #368 still does not work.

**Comment by blankjul** [comment]
I was hoping this pull request #503 has fixed it.

@Deathn0t this is the same issue, right? Does this error still show up when you run the code?

**Comment by Deathn0t** [comment]
Under the following setup:

- Platform: `macOS-14.1.1-arm64-arm-64bit`
- Python: `3.11.6`
- PyMOO: `0.6.1`
- Numpy:  `1.26.1` (looks like the bug was related to numpy arrays such as described in #503)

The example provided in #368 works for me. Example output (last iterations):

```
{'b': False, 'x': 'multiply', 'y': 2, 'z': -2.43547972204905}
{'b': True, 'x': 'nothing', 'y': 1, 'z': -1.1982534166760008}
{'b': False, 'x': 'nothing', 'y': 0, 'z': -0.6758550662203551}
{'b': True, 'x': 'nothing', 'y': 1, 'z': -1.5454435566241478}
{'b': True, 'x': 'multiply', 'y': 1, 'z': -1.4796050350421128}
{'b': False, 'x': 'nothing', 'y': 1, 'z': -1.6717658803548519}
{'b': False, 'x': 'nothing', 'y': 1, 'z': -1.549761579760727}
{'b': True, 'x': 'nothing', 'y': 2, 'z': -0.705162482921279}
{'b': False, 'x': 'multiply', 'y': 0, 'z': -0.0028669449951096437}
{'b': False, 'x': 'nothing', 'y': 1, 'z': -3.3019909955938873}
```

**Comment by NatOnera** [comment]
Thanks a lot for your answer. 
I did some updates and now it seems to be ok.
with OS WINDOWS 10
numpy                     1.23.4
pymoo                      0.6.1
python                      3.9.18

**Comment by blankjul** [comment]
Great! Let me close this issue then.

Thanks @Deathn0t for the quick test as well.
