### ISSUE TITLE
ModuleNotFoundError: No module named 'pymoo.factory'

### ISSUE THREAD

**Issue by sunshineYin** [anyoptimization/pymoo#516]
Hello, thanks for your excellent work! And recently, i have installed `pymoo` on my server, but when i tried to import the functions like `get_sampling`, it failed. The source codes are as follows:

```
from pymoo.factory import get_sampling, get_crossover, get_mutation
```

And the error is as follows:

```
ModuleNotFoundError: No module named 'pymoo.factory'
```
And i want to know why, and look forward to your reply!

**Comment by blankjul** [comment]
What version are you using? Make sure you are using 0.6.1.

Please let me know if that resolve the issue.

**Comment by sunshineYin** [comment]
Thanks for your reply. Yes, i am using 0.6.1. And i have resolved this issue. It seems like these functions need to be imported in a different way, as follows:

```
from pymoo.operators.sampling.rnd import IntegerRandomSampling
from pymoo.operators.crossover.sbx import SBX
from pymoo.operators.mutation.pm import PM
```

**Comment by sunshineYin** [comment]
However, i have met another issue. In my optimization, the `X` must be integers. So i have chosen the IntegerRandomSampling strategy, as follows:

```
algorithm = NSGA2(
    pop_size=100,
    n_offsprings=10,
    sampling=IntegerRandomSampling(),
    crossover=SBX(prob=0.9, eta=3), 
    mutation=PM(eta=3),
    eliminate_duplicates=True
)
```

However, the output are all float types, not integers, as follows. So why? And how to solve it?
```
[ 6.         12.00250296  3.6722074   4.        ]
[ 6.85924768 12.00226928  3.27308655  3.22916062]
[ 2.20565251 12.          9.856295    1.48263341]
[10.26775365  8.56385717  4.52212579  1.97581377]
```

**Comment by blankjul** [comment]
SBX and PM are still operating on floats. Checkout this tutorial: https://pymoo.org/customization/discrete.html
You can also use a `Repair` operator to round off all values at the end of each iteration. both works.

**Comment by ErXiu-d** [comment]
from pymoo.factory import get_sampling, get_crossover, get_mutation

**Comment by ErXiu-d** [comment]
Breaking changes: Factory methods have been deprecated or deactivated (because of maintenance overhead and hiding of constructor parameters)
