### ISSUE TITLE
Problem.bounds() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by cumttc** [anyoptimization/pymoo#521]
My code as follows：
##################
from pymoo.core.problem import Problem as problem_pymoo
lb=np.array([xmin,ymin,zmin])
ub=np.array([xmax,ymax,zmax])
class local_pymoo(problem_pymoo):
    def __init__(self,**kwargs):
        self.s = kwargs.get('s', None)
        self.rcv_i = kwargs.get('rcv_i', None)
        self.num0 = kwargs.get('num0', 0)
        self.num1 = kwargs.get('num1', 0)
        super().__init__(n_var=3, n_obj=1, n_ieq_constr=0,**kwargs)
        self.xl = lb
        self.xu = ub
    def _evaluate(self, x, out, *args, **kwargs):
        out["F"] = fun_local_relativity(x, self.s, self.rcv_i, self.num0, self.num1)
#choose algorithm
algorithm = CMAES(x0=np.random.uniform(lb, ub))
#solve
res = minimize(local_pymoo,algorithm,seed=1,verbose=False,s=s,rcv_i=rcv_i,num0=num0,num1=num1)
-----------------------------------------
TypeError: Problem.bounds() missing 1 required positional argument: 'self'
##########################
As you can see, the variables 'lb' and 'ub' are the upper and lower bounds of the three-dimensional coordinates consisting of three floating-point numbers, respectively (such bounds are set with reference to 'PressureVessel '). But the problem is that it reports an error, TypeError: Problem.bounds() missing 1 required positional argument: 'self'. I can't understand it and need your help.

**Comment by cumttc** [comment]
My code as follows：
-------
from pymoo.core.problem import Problem as problem_pymoo
lb=np.array([xmin,ymin,zmin])
ub=np.array([xmax,ymax,zmax])
class local_pymoo(problem_pymoo):
def init(self,**kwargs):
  self.s = kwargs.get('s', None)
  self.rcv_i = kwargs.get('rcv_i', None)
  self.num0 = kwargs.get('num0', 0)
  self.num1 = kwargs.get('num1', 0)
  super().init(n_var=3, n_obj=1, n_ieq_constr=0,**kwargs)
  self.xl = lb
  self.xu = ub
def _evaluate(self, x, out, *args, **kwargs):
out["F"] = fun_local_relativity(x, self.s, self.rcv_i, self.num0, self.num1)
#choose algorithm
algorithm = CMAES(x0=np.random.uniform(lb, ub))
#solve
res = minimize(local_pymoo,algorithm,seed=1,verbose=False,s=s,rcv_i=rcv_i,num0=num0,num1=num1)
TypeError: Problem.bounds() missing 1 required positional argument: 'self'
------
As you can see, the variables 'lb' and 'ub' are the upper and lower bounds of the three-dimensional coordinates consisting of three floating-point numbers, respectively (such bounds are set with reference to 'PressureVessel '). But the problem is that it reports an error, TypeError: Problem.bounds() missing 1 required positional argument: 'self'. I can't understand it and need your help.

**Comment by blankjul** [comment]
Please provide a well-formatted example of code that is actually runnable and helps to reproduce the error. I am closing this issue. Feel free to create a new one with more information.
