### ISSUE TITLE
DTLZ

### ISSUE THREAD

**Issue by MKermanipoor** [anyoptimization/pymoo#522]
I was wondering are you have a plan to implement the pareto front of DTLZ5, DTLZ6, DTLZ7? 
when I tried to get the pareto font of those functions with 5 objectives, I got "Not implemented yet." error.

**Comment by blankjul** [comment]
I will make it short currently this is not on the agenda. In theory, this needs to be a method to work for any number of objectives which is more challenging to implement by itself. 
However, if you know of a solution I would be very happy to look at a pull request!
