### ISSUE TITLE
Optimization returns an error if termination condition is set

### ISSUE THREAD

**Issue by alibaba613** [anyoptimization/pymoo#526]
I have an optimization problem (NSGA2) that was running to 5000 generations, and I wanted to check convergence issues, so I added the default termination conditions as follows
`termination = DefaultMultiObjectiveTermination(
    xtol=1e-8,
    cvtol=1e-6,
    ftol=0.000025,
    period=30,
    n_max_gen=5000,
    n_max_evals=100000
)

res = minimize(problem,
               algorithm,
               termination,
               #('n_gen',5000),
               verbose = True,
              seed = 42)`
However, with this termination condition (and no matter how I change xtol, cvtol, or ftol) I get this error during the 7th generation: **AxisError: axis 1 is out of bounds for array of dimension 1**
keep in mind that I doubt this is a problem with my optimization function as it runs without problems if I comment termination and uncomment the n_gen criterion.
Any help? I am running version 0.6.0.1

**Comment by blankjul** [comment]
Thanks for reporting a possible bug. Can you provide some example code I can directly run to reproduce this issue?

**Comment by alibaba613** [comment]
Hello Julian, Thanks for the reply. I upgraded to the newest version 6.1.1 and the problem seems to have been solved.

**Comment by blankjul** [comment]
Great and thanks for your quick reply! 
I will close this issue.
