### ISSUE TITLE
Not all optuna imports are guarded

### ISSUE THREAD

**Issue by dkbarn** [anyoptimization/pymoo#530]
In your wrapper module around the Optuna algorithm, you have some of the imports of the optuna library inside a try/except so that a more helpful error message can be provided. But not all of them. There is an import of optuna's logger that lives outside this try/except which renders that try/except pointless.

https://github.com/anyoptimization/pymoo/blob/main/pymoo/algorithms/soo/nonconvex/optuna.py#L3

**Comment by blankjul** [comment]
Thanks for reporting this! The commit above should fix this.
