### ISSUE TITLE
Tutorial with logist regression

### ISSUE THREAD

**Issue by Mairafatoretto** [anyoptimization/pymoo#540]
Hello, I have a problem optimization with train and test dataset. I would like to estimate parameters using my train dataset. There is some tutorial using this?

**Comment by stonebig** [comment]
Maybe This europython 2023 presentation would help ?
 https://www.youtube.com/watch?v=ZNlp5J0e9H4&t=2294s

**Comment by blankjul** [comment]
I have recently answered an issue for ridge regression here: #506

Analgously, logistic regression can be implemented.
