### ISSUE TITLE
MOPSO Implementation

### ISSUE THREAD

**Issue by Leviathan321** [anyoptimization/pymoo#542]
I am not sure if this is the right way to ask, but does someone has maybe a version (local) of the implementation of the multiobjective version of PSO (MOPSO) based on pymoo. I am doing some research using the pymoo framework and that would help me a lot to use it.

**Comment by blankjul** [comment]
If someone has an implementation I am more than happy to look at a PR to include it for everyone!

**Comment by blankjul** [comment]
I will close this for now.
