### ISSUE TITLE
Tutorial Mixed optimization with NSGA-II

### ISSUE THREAD

**Issue by ai1enthusiast** [anyoptimization/pymoo#543]
Hello,

I knew how to launch a mixed optimization with NSGA-II using the factory in the version 0.5.
I would like to go for 0.6 but cannot find how to reproduce that, the doc is pretty unclear on that point, and looking to the implementation makes me wonder if it is possible to do what I want in 0.6.

Could you help me please ?

Thank you very much !

**Comment by blankjul** [comment]
The API has slightly changed. The new tutorial is posted here: https://pymoo.org/customization/mixed.html

**Comment by ai1enthusiast** [comment]
Thank you for you fast answer :)

I was exactly looking at this tutorial, and I guess what is of interest to me is that sentence :

> Moreover, if you intend to solve a multi-objective optimization problem, you can either instantiate existing algorithms with MixedVariableMating 

I had a look in the implementation of MixedVariableMating, but that did not help me so far to guess how NSGA2 could be instantiated in this way :)

**Comment by LoGaL93** [comment]
I have the same/similar problem... It is clear how to define the variable types (mixed of course), but not how to specify sampling, crossover and mutation operators with the relative settings

**Comment by blankjul** [comment]
`Mixed` is implemented to work out of the box. If you want to customize the genetic algorithm I recommend following this tutorial: https://pymoo.org/customization/custom.html

Then you have the full power of how to handle each operator across all variable types. The `mixed` implementation just defines default evolutionary operators for each variable type indepdently.

**Comment by blankjul** [comment]
Regarding the comment 
```
Moreover, if you intend to solve a multi-objective optimization problem, you can either instantiate existing algorithms with MixedVariableMating
```

I just means that you can either instantiate NSGA-II with `MixedVariableMating` or `MixedGA` with `NonDominatedSorting` as survival and both will become a similar algorithm.

I should not that pymoo was originally not designed to handle mixed variables (because in the EA field there is not much research focus on this). However, I wanted to give users an option to use the existing algorithms.

**Comment by ai1enthusiast** [comment]
Much clearer, thank you :)
