### ISSUE TITLE
annoying virustotal

### ISSUE THREAD

**Issue by stonebig** [anyoptimization/pymoo#545]
Since version >= 0.6.1 , and not 0.6.0.1 for example, 1 out of 61 antivirus motor of VirusTotal do complain.

It's not a lot, yet if something could be understand, then done about it I would be nice

![image](https://github.com/anyoptimization/pymoo/assets/4312421/0244172f-8780-4dc2-b2ee-ada390447019)

former 0.6.0.1 zen moments
![image](https://github.com/anyoptimization/pymoo/assets/4312421/30aee7ec-6c82-41d6-b7fe-43e2d38af6d1)

**Comment by stonebig** [comment]
on last build with new Python-3.12:
- same problem with python- 3.11 wheel for windows 64
- zero problem with python- 3.12 wheel for windows 64

painfull world:
![image](https://github.com/anyoptimization/pymoo/assets/4312421/5cf59fac-da8e-469e-8e65-5a656106f942)

**Comment by blankjul** [comment]
Thanks for reporting this. But honestly I don't really know what to do about this.

The wheel files are compiled directly through GithubActions and I just upload them. Do you know of any way to resolve this issue?

**Comment by stonebig** [comment]
Well, no. It's more frequent on python-3.12, so maybe we can just wait anti-virus to cool down.

If you don't guess in the recent code what can have bothered one anti-virus, then we can only wait

**Comment by blankjul** [comment]
100%, agree!
