### ISSUE TITLE
Is there a way to couple two inputs?

### ISSUE THREAD

**Issue by alibaba613** [anyoptimization/pymoo#547]
I'm trying to find a way to couple two inputs. Say I have two features A={1,2,3,4,5,6}, and B={7,8,9,10,11,12}, is there a way to manually override the sampling when running NSGA-II? I'm using `from pymoo.core.variable import Choice` due to the discrete nature of the variables I am using. The code I'm attaching at the bottom is incomplete, as it is not possible for me to post the entirety of my code. If it is too incomplete to understand or answer my question, kindly indicate what should be added to give a more complete picture. Though I do feel like this is more a feature suggestion than a potential issue.
```
from pymoo.core.variable import Choice
mixed_variables={
"A" : Choice(options=[1,2,3,4,5,6]),
"B" : Choice(options=[7,8,9,10,11,12]),
"C":Choice(options=[......]),																																																																																														
 "D" : Choice(options=[.......]),
}
class MOO(Problem):

  def __init__(self, **kwargs):
    super().__init__(vars=mixed_variables, n_obj=3,n_ieq_constr=1, **kwargs)
    def _evaluate(self, x, out, *args, **kwargs):
        x_temp=pd.Series()
        A_index = mixed_variables["A"].options.index(x_temp["B"])
        x_temp["B"] = mixed_variables["B"].options[A]
#code continues here
```
Upon printing x_temp (in the complete code), it indeed shows a coupled relationship between A & B. This does not hold true for any of the optimization results. Is there a way to bypass this?

**Comment by blankjul** [comment]
You can directly pass the initial population as described here: https://pymoo.org/customization/initialization.html
A tutorial for customization is provided here: https://pymoo.org/customization/custom.html

Reading the short description it sounds to me you may want to add a constraint or even a repair:
https://pymoo.org/constraints/index.html
