### ISSUE TITLE
Is fast_best_order_sort intended to be usable by NonDominatedSorting?

### ISSUE THREAD

**Issue by JonathanRaynerMonumo** [anyoptimization/pymoo#563]
#495 has some benchmarks that seem to show good speed for `fast_best_order_sort` from [the cython code](https://github.com/anyoptimization/pymoo/blob/main/pymoo/cython/non_dominated_sorting.pyx#L32), but it doesn't seem to be importable [here](https://github.com/anyoptimization/pymoo/blob/main/pymoo/util/function_loader.py#L22).

**Comment by blankjul** [comment]
I can't recall if there was a reason to make it not accessable. Maybe I wanted to wait until my co-workers paper was officially available. 

Please see my commit above and give it a test if this works now.


```
import numpy as np

from pymoo.util.nds.non_dominated_sorting import NonDominatedSorting

np.random.seed(1)
F = np.random.random(size=(100, 2))

nds = NonDominatedSorting(method='fast_best_order_sort')

res = nds.do(F)
print(res)

```
