### ISSUE TITLE
ModuleNotFoundError: No module named 'optuna'

### ISSUE THREAD

**Issue by zitango** [anyoptimization/pymoo#566]
Hi guys, when I run the code 'from pymoo.algorithms.soo.nonconvex.optuna import Optuna', it makes mistake. I am learning the basic example in the site. https://pymoo.org/customization/mixed.html 
I find my problem cant find one solution, But i can find my bug... how can i find the problem. it's the MILP problem, it can be find solution in the gurobi solver, when i wannt to find d multi-objective, i find it hard to fine only one solution, i have change the problem to       continuous vars problem.

**Comment by blankjul** [comment]
I am not sure what the question is. Please provide reproducable code if you run into an error or ask a conrete question. I will close this ticket for now.
