### ISSUE TITLE
AssertionError: This implementation of MOEAD does not support any constraints.

### ISSUE THREAD

**Issue by niurencheng** [anyoptimization/pymoo#567]
AssertionError: This implementation of MOEAD does not support any constraints.
hello，How to deal with this？  

In pymoo, what algorithm can be selected to solve multi-objective optimization (with constraints), other than GA-related algorithms?
Thanks

**Comment by blankjul** [comment]
NSGA-II and NSGA-III both support constraints.

MOEAD does not because the original paper did not propose a constraint handling approach. I know some papers have propsed an extension. If there is one that robustly works, fee free to contribute to pymoo and push a PR.
