### ISSUE TITLE
Expose algorithm.data 

### ISSUE THREAD

**Issue by jacktang** [anyoptimization/pymoo#570]
Hello,

I wrote some pymoo `Callback`s and store the data into `algorithm.data`, and I found that finally I could not retrieve it from the `Result` object. 

So I think in L256 should add the code
https://github.com/anyoptimization/pymoo/blob/af8d260a5ba34c5e427b671586c32351765419a9/pymoo/core/algorithm.py#L250-L257 

```
res.data = self.data
```

**Comment by blankjul** [comment]
Checkout the commit above and see if it works. Thanks!
