### ISSUE TITLE
Optimisation parameters for integer types

### ISSUE THREAD

**Issue by cumttc** [anyoptimization/pymoo#573]
from pymoo.core.problem import ElementwiseProblem  as Problem2
from pymoo.core.variable import Integer

class local_pymoo(Problem2):
    def __init__(self, **kwargs):
        self.s = kwargs.get('s', None)
        self.rcv_i = kwargs.get('rcv_i', None)
        self.num0 = kwargs.get('num0', 0)
        self.num1 = kwargs.get('num1', 0)
        vars ={'x' : Integer(bounds=(xmin,xmax)),
               'y' : Integer(bounds=(ymin,ymax)),
               'z' : Integer(bounds=(zmin,zmax)),
               }
        super().__init__(vars=vars,n_obj=1,n_ieq_constr=0, **kwargs)

    def _evaluate(self, x, out): 
              
        out["F"] = fun_local_relativity(x,self.s,self.rcv_i,self.num0,self.num1)

As shown above, this is a custom question about positioning. I've referred to 'https://pymoo.org/customization/mixed.html' and set X,Y,Z to 'Integer' but the end result is still a float number .What should I do, please?

**Comment by blankjul** [comment]
What algorithm are you calling? If you follow the code snippet of the homepage you linked and just exchange the problem it should work.
