### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by Fuminides** [anyoptimization/pymoo#578]
I think it would be good to have a package available in one of the popular conda channels. 

A lot of people use Anaconda to handle python enviroments and sometimes pip installing is not an option. I am aware that it is possible to compile it from source but I think it wuld be good to have something on conda forge, for example.

**Comment by cyrilpic** [comment]
There is a package in conda-forge (I am one of the maintainers): https://github.com/conda-forge/pymoo-feedstock. It's synced with the latest pypi release (v0.6.1.1). Are you not able to install it?

**Comment by Fuminides** [comment]
Hello! I see, maybe I have a problem with my local setup and that's why it is not visible from my conda installation.

**Comment by cyrilpic** [comment]
It is compiled for Python versions 3.8 through 3.12 on win64, osx-arm64, osx-64 and linux-64. If you find a specific issue, you can open an issue on the pymoo-feedstock repo. I'd be happy to help.

**Comment by blankjul** [comment]
@cyrilpic Thanks for taking care of it!
