### ISSUE TITLE
The specification of the reference point in the normalized hypervolume calculation

### ISSUE THREAD

**Issue by Peng-YM** [anyoptimization/pymoo#59]
I noticed that the reference point is always set to (1, 1, ..., 1) for the hypervolume calculation when the objective should be normalized. As shown in the following codes:
https://github.com/msu-coinlab/pymoo/blob/6a38bd815afb0289ff52ad02af1e82ca63500166/pymoo/performance_indicator/hv.py#L64

**However, with this specification, solutions on the boundary have no hypervolume contribution.** In this article [Hisao Ishibuchi 2018](https://dl.acm.org/doi/10.1162/evco_a_00226), the author suggested that the reference point should be set to (1.1, 1.1, ...). I think the hypervolume indicator should allow users to specify an alternative point rather than (1, 1, ..., 1) when calculating the normalized hypervolume.

**Comment by julesy89** [comment]
Yes that is right, it should not always be `1.0` to have a more fair comparison. However, just setting it to `1.1` does not work for any number of dimensions. For higher dimensions the formula is `1 + 1/H` where `H` is the partition number assuming a Das and Dennis uniform distribution. 

https://dl.acm.org/doi/pdf/10.1162/evco_a_00226
Section 3.2

Would you like to implement it and do a pull request?

**Comment by Peng-YM** [comment]
Sure, I will create a pull request when I finished it.
