### ISSUE TITLE
How to repair inputs(X) after problem evaluation?

### ISSUE THREAD

**Issue by jacktang** [anyoptimization/pymoo#591]
Hello there!

In my project the problem evaluation is very expensive, and I know how to repair the inputs(X) after the evaluation. In pymoo, the `Repair` operator takes `problem` and `pop` as arguments, which means I have to re-evaluate the problem and get the repaired inputs. How can I pass the evaluation results(repaired inputs included) to the `Repair` operator directory? Thanks!

**Comment by blankjul** [comment]
I am not sure if I fully understand the question. The `Repair` operator is always executed BEFORE the solution is even evaluated.

**Comment by jacktang** [comment]
@blankjul Thanks for your reply!  and yes the `Repair` is executed before problem evaluation. As to the question, I created some cheap `Repair` function through data driven method and solved it.
