### ISSUE TITLE
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap' when using Matplotlib 3.9.0

### ISSUE THREAD

**Issue by a-schimek** [anyoptimization/pymoo#596]
AttributeError caused by new matplotlib version 3.9.0 as described here:

https://github.com/luciddreamer-cvlab/LucidDreamer/issues/56

more info:
https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.0.html

**Comment by blankjul** [comment]
Should be fixed now.
