### ISSUE TITLE
Handling crashes in PSO

### ISSUE THREAD

**Issue by oarcelus** [anyoptimization/pymoo#597]
I am trying to implement a PSO for a model. Sometimes, depending on the combination of input parameters, the model crashes and returns None. How should I handle this case with pymoo? Maybe postprocessing the _evaluate function to give a default value to those cases that crashed?

**Comment by blankjul** [comment]
Yes, I would sorround the third-party code with a try-catch and then set the objective to a large value (or introduce a inequality constraint to be 1 if failed and 0 if it succeeded. both will work)
