### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by c-w-feldmann** [anyoptimization/pymoo#602]
Hey,
I need [these changes](https://github.com/anyoptimization/pymoo/commit/5af46f39c190689e638747e4217f051993e25d10) which were added over a year ago. It's not urgent, but I would like to know when the next version will be released?

**Comment by blankjul** [comment]
I usually create a comprehensive new release (across platforms including documentation compilation) in summer when I have some time of from my day-to-day job and can spend some time on my side-projects.

**Comment by c-w-feldmann** [comment]
Thanks a lot.
