### ISSUE TITLE
Considering duplicates across populations

### ISSUE THREAD

**Issue by Leviathan321** [anyoptimization/pymoo#608]
I am wondering whether there is a mechanism in pymoo to consider duplicates across populations to reduce the evaluation time? I am using the famework for an application where evaluations are expensive simulations. And I get a lot of duplicates sometimes.

I have only encountered so far dupliate elemination for the offspring generation. Is there such a mechanism across populations? Or can maybe someone sketch an appropriate place where this could be integrated?

**Comment by blankjul** [comment]
Yes that is possible. The easiest workaround is to cache all evaluations in your `Problem`. And then simply return the result in your cache once it is hit.

If you work with floats you can will need to define a distance to solutions in your cache and implement the hit based on an `epsilon` parameter.
