### ISSUE TITLE
Documentation Update in Mixed Variable Problem Page

### ISSUE THREAD

**Issue by Lyleregenwetter** [anyoptimization/pymoo#612]
In the mixed variable problem documentation page: https://pymoo.org/customization/mixed.html?highlight=mixed%20variable

the algorithm is initialized using pop, which is outdated and should be pop_size. Currently the example code runs without throwing an error, but the population is not set correctly. 

`algorithm = MixedVariableGA(pop=10)`

should be:

`algorithm = MixedVariableGA(pop_size=10)`

Thats it. Thanks!

**Comment by blankjul** [comment]
Thanks for letting us know and caring about the documentation! 

Can you push a PR for this?

**Comment by Lyleregenwetter** [comment]
Done!
