### ISSUE TITLE
Max_time and Max_gen simultaneously

### ISSUE THREAD

**Issue by cumttc** [anyoptimization/pymoo#647]
According to the manual and the 'DefaultSingleObjectiveTermination', “DefaultTermination”, “get_ termination”, it does not seem to be supported.

**Comment by blankjul** [comment]
Not by default but check out this example
https://github.com/anyoptimization/pymoo/blob/main/examples/termination/multiple.py

You can combine and fire the termination if any of multiple termination objectes are satisfied.

Does that resolve your issue?
