### ISSUE TITLE
Issues with Numba in AGE-MOEA

### ISSUE THREAD

**Issue by oliverweissl** [anyoptimization/pymoo#661]
I get the following error when using AGE-MOEA:

```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of type(CPUDispatcher(<function point_2_line_distance at 0x735c3d5b7a60>)) with parameters (array(float64, 2d, C), array(float64, 1d, C), array(float64, 1d, C))

During: resolving callee type: type(CPUDispatcher(<function point_2_line_distance at 0x735c3d5b7a60>))
During: typing of call at /../../miniconda3/envs/***/lib/python3.9/site-packages/pymoo/algorithms/moo/age.py (249)


File "../../../miniconda3/envs/***/lib/python3.9/site-packages/pymoo/algorithms/moo/age.py", line 249:
def find_corner_solutions(front):
    <source elided>
    for i in range(r):
        dists = point_2_line_distance(front, np.zeros(n, dtype=np.float64), W[i, :])
        ^
```
My package versions:
- numba==0.53.1
- pymoo==0.6.1.3
- numpy==1.22.4

Im using the optimizer for a NxG sized array of floats ranging [0,1]. As feedback we get a Nx2 sized fitness array also ranging [0,1].
The approach works for all Pymoo MOO algorithms without numba. 

If you need any further information LMK!

**Comment by oliverweissl** [comment]
Made a fix that works for my case in #662.
Seems to be general enough to be useful for all.

**Comment by blankjul** [comment]
Just merged your PR! Thanks!

**Comment by blankjul** [comment]
In case that should not fix it please re-open this issue.
Note for testing it you will have to use the most recent main branch.
